### ISSUE TITLE
Frequency list shows 200 mhz more then real frequency is.

### ISSUE THREAD

**Issue by McRobber** [PredatH0r/ChanSort#112]
Hi
ChanSort shows me a wrong frequency list of my Samsung UE55HU8580. For example the frequency for a particular transmitter is 498 Mhz. ChanSort shows 698 Mhz (it calculates 200 Mhz too much).
This problem are on all DVBC transmitters. Even, it's not a real problem. The application work fine but it would be nice to fix this small problem.
![grafik](https://user-images.githubusercontent.com/29205992/39966057-8c886932-56a5-11e8-9a85-d8dd1a3d1313.png)
If you need more information, please let me know.

Regards
Marcel

**Comment by McRobber** [comment]
Hi 
I've an additional information. I made some tests. So I tested the version from 2015/April, 18th. With this version it displayed the correct frequency. The version from 2015/October, 15 displayed the wrong frequency (200 Mhz too much). 
I hope this helps with debugging.

Regards
Marcel

**Comment by McRobber** [comment]
sorry, closed by accident....

**Comment by PredatH0r** [comment]
fixed in https://github.com/PredatH0r/ChanSort/releases/tag/v2019-07-16
