### ISSUE TITLE
Unable to open list from Panasonic VT60

### ISSUE THREAD

**Issue by laserjet6** [PredatH0r/ChanSort#119]
Hi,
First of all, I love Chansort. 
I have been using Chansort to sort channels on my Panasonic VT60 since 2015 and all worked fine. 
Now, I cannot open the exported list / nor the sorted lists I saved earlier. 
Last time I am sure it worked was on 14 April 2018 when I last sorted the channels. I cannot open the same file now using both the 2017-11-30 or 2015-10-15 versions. 
I have Visual C++ 2010 x86 Redistributable installed (version 10.0.40219)

![image](https://user-images.githubusercontent.com/45206838/48783882-bdbee080-ece1-11e8-8f57-307d6648f876.png)

What I can think f is that  my Win 10 Pro was updated since then and now I get error:

**Comment by PredatH0r** [comment]
Could you send me the file?
Might have been a file-locking issue that some other program (maybe a minimized ChanSort window) blocked the needed write access. Do you still have the problem after rebooting your computer?

**Comment by laserjet6** [comment]
Thanks for replying. 
I figured it out. The file was on a network share. As soon as I moved it to local storage, it opened just fine.
