### ISSUE TITLE
Toshiba 32HL933G - am I cursed?

### ISSUE THREAD

**Issue by Gordon-Dry** [PredatH0r/ChanSort#124]
For years now - about once a year - I try to find a way to sort the exported channels  list of the Toshiba 32HL933G, which is a HOTEL_933X.BIN

No single software was capable of opening it. Even ToshibaEdit was not able to, after zipping the .bin as intended.

The most referenced and most up-to-date software is yours.

But also still no avail.

Did I just buy the most bad junk TV set ever?
It's several years old now, but I still hope I will finally be able to sort the channels list on my PC ...

**Comment by Gordon-Dry** [comment]
A dropbox link to my last exported file:
https://www.dropbox.com/s/7j1bixicv4nt1ns/HOTEL_933X.zip?dl=1

**Comment by PredatH0r** [comment]
Toshiba uses several different file formats for different TV models. 
ChanSort can only work with lists that use a .zip file containing a chmgt_type001/chmgt.db file.

Lists that use files like "dtv_cmdb_1.bin", "tcl_clone_user.bin" or "hotel.bin" are unfortunately not supported. They use undocumented proprietary data formats.
