### ISSUE TITLE
Crypt channels not showing on Samsung UE32D5500

### ISSUE THREAD

**Issue by brainhex** [PredatH0r/ChanSort#126]
Hello,

Im trying to put scambled DVBC channels showing in channel list.
At the moment, with the attached channel config,i can only zap channels with P-/P+ and inserting channels number.
Its indifferent if i check/uncheck the hide option

I use the last version on chansort.

[channel_list_UE32D5500_1101.zip](https://github.com/PredatH0r/ChanSort/files/2824675/channel_list_UE32D5500_1101.zip)

**Comment by brainhex** [comment]
In  Ue32Q5525 work ok, i test yesterday.
In the Ue32D5500 is like that chansort dont assume the correct "hidden" option.
After channel search all appear with the hidden optiin checked, but in fact some are and others not.
Can anybody help solve?

Thanks

**Comment by PredatH0r** [comment]
Can you send me a channel list with both hidden and unhidden channels and let me know an example of each type? I can then take a closer look. horst (at) beham (dot) biz
The D and Q series use completely different channel list formats, so it is quite possible that hiding channels works for one and not the other.

**Comment by PredatH0r** [comment]
Added some special handling in version 2019-02-10 that when the "hidden" flag in the channel list has value 255 (=undefined) another byte will be used to best-guess the correct "hidden" status.
