### ISSUE TITLE
Adding channels to sorted list does not work

### ISSUE THREAD

**Issue by Double-A-92** [PredatH0r/ChanSort#128]
If I have an empty sorted list (on the left) I cannot add selected channels (from the right) to it.  As a workaround I can add _all_ channels to it and then remove the ones that I don't need.

[channel_list_UE46F5000_1201.zip](https://github.com/PredatH0r/ChanSort/files/2871796/channel_list_UE46F5000_1201.zip)

**Comment by PredatH0r** [comment]
Works without a problem for me.
After loading your file, I selected "Create new list: Start with an emty list ..."
My insert mode is set to "after", on the left pane I have the "Pr#" tab selected.
Then I just have to double-click a channel in the right pane to add it to the left pane.

**Comment by Double-A-92** [comment]
I just realised that the blue arrow works, but the righ-click context menu does not.

**Comment by PredatH0r** [comment]
I see. You are right... that (green +) "Add Channels" has no function at all behind it.
It will be fixed in the next release to use the same blue arrow symbol and the same function as the button.
