### ISSUE TITLE
Problem printing

### ISSUE THREAD

**Issue by xsandro** [PredatH0r/ChanSort#129]
Problem printing on version 12-02-19

**Comment by xsandro** [comment]
![capture26-02-2019-17 22 08](https://user-images.githubusercontent.com/37487511/53428504-3624f400-39eb-11e9-926b-b3ee4b29f711.jpg)

**Comment by filmfreund** [comment]
same problem here
![chansort-error](https://user-images.githubusercontent.com/48995022/55086693-1a277780-50a9-11e9-91ba-d144bfff3e19.png)

**Comment by Si2Bim** [comment]
Having the similar issue
![grafik](https://user-images.githubusercontent.com/7913834/55279520-b061d480-5319-11e9-8c7d-94bf8a00ce32.png)
guess - something to do with "upgraded to DevExpress 18.2"
vers. "ChanSort 2017-11-30" works......

**Comment by PredatH0r** [comment]
fixed in version 2019-07-13
(added missing DLL)
