### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by corteum** [PredatH0r/ChanSort#135]
if I want to drag my .scm file and drop it on Chansort.exe it doesn't work, it opens blank table as usual. Can you add reading of parameters so t would be possible?
I want to add .scm extension association on Windows to just click on icon so it would be helpful.

**Comment by PredatH0r** [comment]
added in version 2019-07-13
drag/drop, command line parameter and in the "Settings" menu an option to enable/disable Explorer Integration
