### ISSUE TITLE
Could not open Sony file

### ISSUE THREAD

**Issue by sehroriginell** [PredatH0r/ChanSort#137]
There is an error message when trying to open the file. It's from the newish Sony AF9.

I had to rename the file from .xml to .txt in order to upload it to Github.

Tested with ChanSort 2019-07-16.

[sdb_neu.txt](https://github.com/PredatH0r/ChanSort/files/3402240/sdb_neu.txt)

**Comment by PredatH0r** [comment]
Thanks for your feedback.
I started looking into this and hopefully will have a fix soon.

From what I can tell now, the current ChanSort version does not support the DVB-C lists in the specific file format version your TV uses (which includes a "<FormateVer>1.1.0</FormateVer>" identifier).

**Comment by PredatH0r** [comment]
Fixed now in https://github.com/PredatH0r/ChanSort/releases/tag/v2019-07-18
