### ISSUE TITLE
Samsung UE40ES7080 to QE55Q7FN 

### ISSUE THREAD

**Issue by Si2Bim** [PredatH0r/ChanSort#138]
How do I go about importing the .scm file from my previous TV (UE40ES7080) to my new (QE55Q7FN) TV. The new one does not seems to be able to read that file.
The Q TV does not seems to have an option to import/export the favorite list.
No MENU - just Setting.

**Comment by PredatH0r** [comment]
Hi!

 

This works a bit differently. You can’t import a file with a different format directly into the TV, nor can ChanSort convert formats.

But what you can do is run a full channel search on your new TV, export that list to USB and open it with ChanSort.

When asked, pick the open to apply a reference list and then select the list from your old TV.

ChanSort will bring the channels into the same order then. Favorites can only be copied when the systems are compatible.

 

Regards,

Horst

 

Von: Si2Bim <notifications@github.com> 
Gesendet: Sonntag, 21. Juli 2019 03:10
An: PredatH0r/ChanSort <ChanSort@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [PredatH0r/ChanSort] Samsung UE40ES7080 to QE55Q7FN (#138)

 

How do I go about importing the .scm file from my previous TV (UE40ES7080) to my new (QE55Q7FN) TV. The new one does not seems to be able to read that file.
The Q TV does not seems to have an option to import/export the favorite list.
No MENU - just Setting.

**Comment by Si2Bim** [comment]
Hallo Horst
Thanks for the info. Will try it out accordingly.
Regards
Tom
