### ISSUE TITLE
sony XG7096 error on Chansort

### ISSUE THREAD

**Issue by cosmyn198304** [PredatH0r/ChanSort#151]
Hello All,

I am trying to sort a list exported from a Sony XG7096 , a sdb.xml document, The program reads it ok , shows the list and all , but when i try to save it it gives me an error, no matter what i do ( even if i change nothing ) 
![sony XG7096](https://user-images.githubusercontent.com/57572422/68533815-201b5180-0336-11ea-98ed-3b2ac9c76f45.JPG)

Could you please help ?
thank you!

**Comment by PredatH0r** [comment]
Can you please send me your list?
What kind of changes did you try? Just reordering or also deleting channels?
Did you use the latest ChanSort version (that was released today) or an older version?

**Comment by cosmyn198304** [comment]
Hi PredatH0r

Yes , i have tried today's version as well. The simpliest thing i tried is open the list and save it with a different name, without other changes.  

[sdb.zip](https://github.com/PredatH0r/ChanSort/files/3827744/sdb.zip)

**Comment by PredatH0r** [comment]
I uploaded a pre-release version that can load and save your list: http://chansort.com/ChanSort_2019-11-10.zip

I am currently adding a couple more changes and will release a new official version maybe later today. This should then include individual sorting of favorite lists for Sony Android TVs.

**Comment by cosmyn198304** [comment]
It works absolutely superb! You spared me a lot of work! Thank you very much!
