### ISSUE TITLE
Philips DVBC.xml result in exception

### ISSUE THREAD

**Issue by mariusft** [PredatH0r/ChanSort#152]
Following message is returned while attempting to load DVBC.xml

```
ChanSort.Loader.PhilipsXml.dll (Philips .xml): System.OverflowException: Value was either too large or too small for an Int32.
   at System.Decimal.ToInt32(Decimal d)
   at System.Decimal.op_Explicit(Decimal value)
   at ChanSort.Api.LookupData.GetDvbcChannelName(Decimal freqInMhz)
   at ChanSort.Loader.PhilipsXml.Serializer.ReadChannel(ChannelList curList, XmlNode node, Int32 rowId)
   at ChanSort.Loader.PhilipsXml.Serializer.Load()
   at ChanSort.Ui.MainForm.GetSerializerForFile(String inputFileName, ISerializerPlugin& hint)
```

If I've guessed right from example file for which Philips plugin was created appears that Frequency="306" (ChannelMap_110) but in my case Frequency="306000000" (ChannelMap_100), stripping out the leading "000000" will import this file.

ChannelMap_100
```
<Channel>
	<Setup ChannelNumber="10" ChannelName="0x50 0x00 0x61 0x00 0x72 0x00 0x61 0x00 0x6D 0x00 0x6F 0x00 0x75 0x00 0x6E 0x00 0x74 0x00 0x20 0x00 0x43 0x00 0x68 0x00 0x61 0x00 0x6E 0x00 0x6E 0x00 0x65 0x00 0x6C 0x00 " ChannelLock="0" UserModifiedName="0" LogoID="0" UserModifiedLogo="0" LogoLock="0" UserHidden="0" FavoriteNumber="0" Scramble="0" />
	<Broadcast ChannelType="3" Onid="1" Tsid="104" Sid="357" Frequency="386000000" Modulation="64" ServiceType="1" SymbolRate="6900" SystemHidden="0" Bandwidth="8" DecoderType="2" SubType="0" NetworkID="0" StreamPriority="0" />
</Channel>
```

**Comment by PredatH0r** [comment]
Could you send me your channel list file please?
I will add it to my sample data and make sure it will be loaded correctly.

ChanSort currently handles 2 quite different Philips XML channel list formats, for one format it already handles these large numbers, for the other it doesn't.

I uploaded a pre-release of ChanSort to http://chansort.com/ChanSort_2019-11-11.zip (2nd update today), which hopefully loads your file correctly.

**Comment by mariusft** [comment]
Tested ChanSort 11.11.2019 and it seems to work.
Here it is ChannelMap_100 
[PhilipsChannelMaps.zip](https://github.com/PredatH0r/ChanSort/files/3833178/PhilipsChannelMaps.zip) for your reference.

**Comment by PredatH0r** [comment]
This is now part of the official version 2019-11-17.
