### ISSUE TITLE
ChanSort 2019-11-25 brakes compatibility with Philips ChannelMap_100

### ISSUE THREAD

**Issue by mariusft** [PredatH0r/ChanSort#153]
Seems this last update broke the compatibility with Philips ChannelMap_100

![channelmap_100](https://user-images.githubusercontent.com/18675921/70531132-fb94de00-1b5c-11ea-8bbb-4983a2931377.jpg)

Previous version 2019-11-18 works.

**Comment by PredatH0r** [comment]
Fixed in https://github.com/PredatH0r/ChanSort/releases/tag/v2020-01-02_2
