### ISSUE TITLE
Senderliste speichern

### ISSUE THREAD

**Issue by Laie-absolut** [PredatH0r/ChanSort#154]
Hallo, Kann ich mehrere Senderlisten auf einem Stick speichern? Gruss Walter

**Comment by PredatH0r** [comment]
Pauschal lässt sich das leider nicht beantworten.
Für Fernseher unterschiedlicher Hersteller ist das normalerweise kein Problem.
Die meisten Fernseher erwarten einen fest durch die Firmware vorgegebenen Dateinamen, wodurch es dann zu Überschneidungen kommen kann, wenn mehrere Listen des gleichen Herstellers auf den Stick gespeichert werden sollen.
Samsung fügt die Modellbezeichnung in den Dateinamen ein, wodurch hier mehrere Listen möglich sind. 
Die meisten anderen Hersteller verwenden für verschiedene Modelle den gleichen Dateinamen, z.T. sogar mit unterschiedlichem Inhalt, wodurch dann Probleme vorprogrammiert sind.
