### ISSUE TITLE
ChanSort_2019-12-29 error when "Apply order from reference list"

### ISSUE THREAD

**Issue by FilipeAmadeuO** [PredatH0r/ChanSort#155]
I receive the following error when i select the "Apply order from reference list" option.

![Chansort](https://user-images.githubusercontent.com/28999876/71600060-55c60500-2b45-11ea-9903-6003e18d7554.jpg)

**Comment by ThiefMaster** [comment]
Same problem for me; downgrading to the previous version helped.

**Comment by FilipeAmadeuO** [comment]
Yes. Previous version works ok

**Comment by PredatH0r** [comment]
Thanks for reporting this. Should be fixed in the latest release: https://github.com/PredatH0r/ChanSort/releases/tag/v2019-12-31
