### ISSUE TITLE
Problem opening file channel.db Hisense H50B7700UW

### ISSUE THREAD

**Issue by hawk2345** [PredatH0r/ChanSort#156]
Problem opening file channel.db Hisense H50B7700UW (Android TV)
![hisense H50B7700UW](https://user-images.githubusercontent.com/36705097/71662206-52a36280-2d59-11ea-8240-e2edb94556ac.png)

**Comment by PredatH0r** [comment]
Can you please send me your channel list for inspection?
(Either as an attachment here or via email to horst @ beham . biz)

**Comment by hawk2345** [comment]
Thank you for your interest in the problem.
I packed channel.db in a zip archive:
[channel.zip](https://github.com/PredatH0r/ChanSort/files/4015879/channel.zip)

**Comment by hawk2345** [comment]
Add info:
B7700UW in other countries Hisense 50RG (50A7010EA).

**Comment by PredatH0r** [comment]
Thanks!
I am already working on it. 
Your particular file has different names for the data columns in the favorites table. I'll be uploading a new release later today when it can load your file too.

**Comment by PredatH0r** [comment]
This is now fixed in https://github.com/PredatH0r/ChanSort/releases/tag/v2020-01-02

**Comment by hawk2345** [comment]
Thanks! Success!

**Comment by westilover** [comment]
Also having problems with a hisense TV - when I try to open the channel.db ChanSort tells me "svl_*tables" - any suggestions how to sove the issue?

Thanks
Sascha

**Comment by PredatH0r** [comment]
Hi Sascha,

Can you upload your channel list or mail it to: horst at beham . biz?
I suspect that the TV exported either an empty database or uses a new format that I haven't seen yet.
An empty list is exported when the TV was set up with a predefined channel list (e.g. "Astra 19.2") that the TV doesn't allow to be modified. It's important to run a full channel search without selecting a specific provider.
