### ISSUE TITLE
Sony WD75: TV do resort my sorted channel list

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [PredatH0r/ChanSort#158]
I am using SAT TV on a Sony WD75 TV.

I exported the channel list on an USB stick an rearranged the list with your nice ChanSort.
After re-importing the list on the TV I can see my new sorting.

But after some seconds the TV starts to switch between some channels, deleting some channels ("no service"), etc I am confused. It looks like that the TV reorderes the channel list again. But not into the state of the original initial channel sorting after my first "station search".

Why does this happen?

I also deactivated the "Automatic refresh services" (translated from German: "Automatische Aktualisierung von Diensten") in the SAT settings menu.

There are no other TV signals (cable, etc) on that TV.

**Comment by PredatH0r** [comment]
Can you please upload or mail me your TV channel list files (the original that ChanSort saved as a .bak file and the modified file)?
After comparing the 2 I can hopefully get some insights on what might cause the TV to react that way.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Here you are. Thanks a lot for checking on this.

**Comment by PredatH0r** [comment]
I made some improvements in https://github.com/PredatH0r/ChanSort/releases/tag/v2020-02-02 regarding Sony channel lists.
Hopefully this will produce valid files now. 
Please use a "clean" files from your TV, or rename the .bak file created by chansort. Don't continue editing files that were already edited before, as they are broken.

Please let me know if it works (or doesn't)

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thanks a lot for your quick response.
I will do a full test in the next two weeks and give you feedback.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
**Version Problems**
The version (2020-02-02) you linked in your last comment was just the sources. I do not know how to build this or even have a usable build environment here.
So I used the (2020-02-04) version you release also. You mentioned there this is the same as 2020-02-02 just with the missing ini file.
Is this OK?

I started `ChanSort.exe` from the 2020-02-04 zip I downloaded and extracted.
The title bar tells me "ChanSort 2020-02-02". It also tells me that a new version "v2020-02-04" is availble.
I did not open the new download.

You can find the original channel list fresh and untouched produced by my TV after a fresh and full station search in `00 sdb - fresh and untouched after station search.xml`.

**Frist Test**
I opened the xml file via ChanSort. Just for testing I did only tiny modificatons.
 - (on the left side of ChanSort) "3sat HD" (original on pos 10) moved to pos 1
 - (on the right side of ChanSort) "ServusTV HD Deutschland" (on pos 11) deleted
    -> ChanSort asked me what to do: I decided to attach and hide the deleted channel at the end of the list.
 - (on the right side of ChanSort) "RTL Television" (on pos 4) deleted
    -> I decided to just "delete the channel"
    
I started my TV and improted the channel list. I watched 10 minutes and longer then the last time. I check pos 1, 4 and 11 to see if my modifications are really there. Fine. Nothing wrong. No automatic reordering. Everything as expected.

But this was just a small test.

In the next test I tried to reproduce my real modifications from the last time after them I perceived the automatic reordering from my TV.

*Second Test**
Again I used the fresh and untouched channel list after a station search.

 - First I deleted a lot of channels on the right side of ChanSort.
   I filtered via "Service Typ" and viewed and delted everything except "HD-TV" and "SD-TV".
   -> 248 deleted -> 997 channels left
 - I ordered by channel name and removed all channels without a name or with a "un-normal" name
   -> 943 left -> renumbered in that ordering
 - I gave "NHK WORLD-JPN" on pos 518 the new pos 1

Saved and imported to TV.

Everything looks fine. Currently no automatic resorting.
Thanks a lot.
