### ISSUE TITLE
Does not import channels of Q60R series

### ISSUE THREAD

**Issue by drtp** [PredatH0r/ChanSort#166]
Hello,

I can use ChanSort without any problems with our Samsung GQ65Q9FN. However, with our newer GQ55Q60R there are not shown any channels. The respective zip file can be imported by SamyCHAN flawlessly. 

Best regards,

Thorsten

**Comment by PredatH0r** [comment]
Can you send me your zip file please so I can take a look?

**Comment by PredatH0r** [comment]
This Model uses the "1352.0" firmware and file format, which seems to works differently than the other known Samsung formats. Support for it is work-in-progress and ChanSort 2020-03-20 should now show the channels in your list again.

**Comment by drtp** [comment]
Thanks a lot. I will give it a try today evening.
