### ISSUE TITLE
Weird problem with GlobalClone00001 files from LG.

### ISSUE THREAD

**Issue by hotshotbg** [PredatH0r/ChanSort#184]
When I export the channel list from my two LG TV's - one with WebOS and one basic TV without OS, I get a very strange error.
The exported file has a name: GlobalClone00001.TLL and it's working fine in the editor but if I change the file name to something different (LG 28inch TV.TLL) suddenly the editor says that there is no plug in for reading this file and opens a blank window.

If I enter GlobalClone00001 somewhere in the filename (LG 28inch TV - GlobalClone00001.TLL) - the file works normally and opens like nothing happened.

Is this a normal behaviour or am I missing something?  :(
![1](https://user-images.githubusercontent.com/25564998/89926216-39c32f80-dc0d-11ea-974c-8c705617901d.PNG)
![2](https://user-images.githubusercontent.com/25564998/89926218-3a5bc600-dc0d-11ea-9e5a-298c1a596115.PNG)

?

**Comment by PredatH0r** [comment]
That is normal behavior that comes with the logic how ChanSort selects a "ChanSort.Loader.*.DLL" file to load a file.

All the different file formats have their own loader DLL. Each DLL defines a file name / extension pattern that it can handle. ChanSort then selects based on the actual file name which loaders might be able to load the file - and skips the others.

LG's XML text based "GlobalClone" format is handled by ChanSort.Loader.GlobalClone.dll, but it will only be used if the file has "GlobalClone" in the name.
LG's binary file formats, typically xx*.TLL with a model number in it, will be handled by ChanSort.Loader.LG.dll. 

If none of the loaders succeeded, ChanSort shows the error messge that each attempted loader returned.

In any case, the TV can only import the file with the exact same name that it exported it, so renaming only makes sense for the case of archiving a list on the PC. In that case, just keep "GlobalClone" somewhere in the file name and ChanSort will be able to select the correct loader.

**Comment by hotshotbg** [comment]
Thank you for the explanation. Thought it was some strange behaviour on my end. : )
