### ISSUE TITLE
Freesat UK Channel Reference Lists

### ISSUE THREAD

**Issue by michael-t1990** [PredatH0r/ChanSort#185]
[gb_astra282E_freesat.txt](https://github.com/PredatH0r/ChanSort/files/5081368/gb_astra282E_freesat.txt)
[gb_astra282E_freesat_16082020_EastAnglia_OrderStartAt1_Tested.txt](https://github.com/PredatH0r/ChanSort/files/5081369/gb_astra282E_freesat_16082020_EastAnglia_OrderStartAt1_Tested.txt)

Firstly thank you for making this software, it’s saved so much time in trying to arrange TV Channels on Free-to-air satellite!

I noticed you’re looking for Channel lists people can use and I’ve used your formatting, and an export from my Hisense TV’s Satellite tuner to create some known working reference lists.

A couple of adjustments made:
1)	Hisense Satellite can receive Channel 4 HD unlike Freesat boxes, so I’ve replaced Channel 4 SD with HD on pos. 4
2)	My Hisense TV appears to need to start @ pos. 1 so This list starts at Pos. 1 not 101

I’ve also attached a more true to freesat copy without the above amendments in case required. This one has not been merged with my Hisense.

It’s otherwise a direct and up to date export as of today.

Hope it helps,

Michael

**Comment by PredatH0r** [comment]
thx for this. forgot to add a note here that i added your files to chansort some time ago

**Comment by michael-t1990** [comment]
Hehe no worries at all thanks for adding them.
