### ISSUE TITLE
How to INSERT (NOT: swap) dragged channels?

### ISSUE THREAD

**Issue by clsven** [PredatH0r/ChanSort#186]
When I drag a channel from position e.g. 39 to list position 12
then the previous channel on position 12 is moved to position 39.
Both channels switched.

I don't want this.
Instead previous channel on list position 39 should be INSERTED on (=before) position 12.
Hence the old channel on position 12 should be shifted 1 position down (to new position 13).

How can I achieve this?

Claudia

**Comment by PredatH0r** [comment]
Between the menu bar and the channel list there is a radio button group named "Edit mode" where you can switch between "swap", "insert after" and "insert before". The 2 different insert modes matter when you just double-click a channel in the right hand side list.
When you drag/drop the insert position depends on the mouse cursor position
