### ISSUE TITLE
Opening File not possible with double click on latest version 2020-08-27

### ISSUE THREAD

**Issue by sensatag** [PredatH0r/ChanSort#191]
Hello
We use your tool almost daily and are very happy with it.
I've just seen that it's not possible to open shortcut which goes into my folder where i have the files...
see screenshot.
if i open a shortcut it tryes to open the file and says it doesn't work. instead of opening the file it should go to the shortcut direction...
![Shortcut](https://user-images.githubusercontent.com/63778856/94821368-cb773e00-0401-11eb-96d4-3e671e85090e.jpg)
would be great if you could change this.

thanks a lot
Philipp

**Comment by PredatH0r** [comment]
Thanks for the report.
I can replicate this behavior, which seems to be a bug (or undocumented behavior) in .NET.
It should (by default) follow links to their target, but it doesn't seem to do that when "*" is added to the file name filters.
After removing "*" (which was added for certain Philips files which do not have an extension), it works again to double-click short cuts to folders.
It will be included in the next upated, but there is no ETA for that yet

**Comment by PredatH0r** [comment]
fixed in version 2020-11-16
