### ISSUE TITLE
Cannot transfer channel list from one Samsung to another

### ISSUE THREAD

**Issue by S-Sokol** [PredatH0r/ChanSort#193]
Good day.
The first TV is UE48H6230, the second - UE40D5000. After export list from first TV I (without any change) try to import it to the second one, but see "Error in list" (sorry, I cannot give the exact text of the error, because it is on another language).
Channel list format is 1201, but on the 2nd TV - 1101. File (inside the archive) is in attach

[channel_list_UE48H6230_1201.zip](https://github.com/PredatH0r/ChanSort/files/5327328/channel_list_UE48H6230_1201.zip)

**Comment by PredatH0r** [comment]
These TVs use different/incompatible firmware and channel list formats, so a direct import is not possible.

With ChanSort you can do the following:
- keep a copy of your already sorted list from one TV
- run a full channel search on the new TV, export that list and open it in ChanSort
- when asked, select the option to apply the order from another list (=reference list)
- select the list from your old TV as the reference list
- save the new list and import it in your new TV

**Comment by S-Sokol** [comment]
Thanks!
