### ISSUE TITLE
Info about LG .TLL file tags: how to recognize DTV channles from SAT ones

### ISSUE THREAD

**Issue by joeongithub** [PredatH0r/ChanSort#196]
Hi! thank for your work here.

As in subject I'm wondering about the meaning of various tags read in TLL file from my lg smart tv with WebOS.
Some channel can't be moved from its automatically sorted program, so I decided to use your tool and It worked good.

Now I'm trying to create a little list of channels, let say 20 channels sorted as I'd like to find them, and placed in the first 20 positions.
I want create a little bash script to change prgnumber of that 20 channels and set it to each of their position in my list.
It's a sort o f reference list, as intended also in Chansort tool.
I want to set just that 20 channels, and let the others as the are.

The problem is that I noticed some program number ( **`<prNum>*</prNum>`** tag) is a duplicate and refer to more than a channel.
I suspect some of them is related to different receiver sources: Satellite and DTT.

Now, is there a way to know if a channel of my TLL file is received from digital terrestrial  television DTT or form SAT?
For instance it is possible to know if it is a radio station or a tv channel thanks to **`<servceType>`** tag...
Is there any other tags referring to the transmission source type sat/terrestrial?

Thanks in advance!  :)

**Comment by joeongithub** [comment]
Maybe I got it!

Seems the tag:

<usSatelliteHandle>

In my TLL file It seems to assume value:
- "9" for SAT channels
- "0" for DTT ones

Now I can check if that was the issue of multiple channels with the same program number.
Any confirm is welcome! :)

**Comment by PredatH0r** [comment]
Hi!

You can find the relevant source code here: https://github.com/PredatH0r/ChanSort/blob/e1e2c8d305d33b7b794ee63abe22c237e17a71bf/source/ChanSort.Loader.GlobalClone/GcXmlSerializer.cs#L254

The "sourceIndex" defines the input source. 2 is digital cable, 7 is digital satellite. I'm not entirely sure if DVB-T is 1 or 3.
I guess that "usSatelliteHandle" means "unsigned short SatelliteHandle" and is some sort of reference to the satellite table - but only valid for real satellite channels.

**Comment by joeongithub** [comment]
Thanks! Really useful info!

I tested a really raw bash script that reads a sort of favorite channels list (simple CSV format), and edit original TLL file.
I found the tags to edit are just 2:

1) prNum

In my procedure a "swap" is executed: if I want mychan on program 10 I save its original prNum, let's say 123 and set it to 10, then set original `<prNum>10</prNum>` referring to an other channel to 123, In other words swap 10 with 123 editing their related two prNum lines.

2) isUserSelCHNo

This tag has to be set to 1, if I let it as is, set to "0", when I upload channels in my LG TV, the list rest unchanged. Maybe my changes regarded some LCN channel "locked" in that position, anyway without this tag set to 1, sort didn't work at all.


Could you confirm these tags are the only two to be edited in order to change channels position in the list?
Thank a lot again for your answer!
Bye!
