### ISSUE TITLE
Samsung hg43ej690u

### ISSUE THREAD

**Issue by eagle500** [PredatH0r/ChanSort#198]
Hello and thank you for this program. I have been using it for a long time with normal Samsung and LG tv's . I just bought a ""hospitality"" tv HG43EJ690U and I can't make Chansort open the files exported by the tv. Maybe you can take a look ? I read the thread where another guy has the same problem but with a different model, but maybe in my case the files are more "readable". Thank you. 

[Channel_list_T-KTM2DEUCB-1120.1.zip](https://github.com/PredatH0r/ChanSort/files/5569852/Channel_list_T-KTM2DEUCB-1120.1.zip)

**Comment by PredatH0r** [comment]
I had no problem opening this file with ChanSort (Version 2020-11-16) and see 190 channels there.
Please make sure to open the .zip file with chansort and not any of the files that are inside the zip.
Or was there another issue like missing data after opening the file?

**Comment by eagle500** [comment]
I made a mistake trying to load the individual files in the zip file, not knowing that I could load the zip file directly. All solved now. Thanks again.
