### ISSUE TITLE
LG OLED65GX3LA - System.NullReferenceException error when selecting channel list file to open

### ISSUE THREAD

**Issue by AndreiContributor** [PredatH0r/ChanSort#200]
Hi,

I exported the list from the TV in the file attached, but when I open the file with the application I get the error:

---------------------------
Fehler bei Programmausführung
---------------------------
Bei der Programmausführung trat folgender Fehler auf:
System.NullReferenceException: Object reference not set to an instance of an object.

   at ChanSort.Ui.ReferenceListForm.SetInput(SerializerBase ser)

   at ChanSort.Ui.ReferenceListForm.<OnLoad>b__6_0()
---------------------------
OK   
---------------------------

Regards
[GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/5594699/GlobalClone00001.zip)

**Comment by PredatH0r** [comment]
Hi Andrei,
Unfortunately the .zip file attached is corrupted. It only contains bytes with value 0 and can't be opened.
I've seen numerous cases where the TV write files with all 0 or some garbage on a USB stick.
Typical causes are 
a) fake USB sticks that report more memory than they actually have or containing bad memory cells, resulting in data loss
b) sticks formatted with a file system that's not fully supported by the operating system of the TV or PC (expecially NTFS-sticks can cause trouble when writing on them with a linux based TV)

**Comment by PredatH0r** [comment]
Recent versions of ChanSort no longer show a NullReferenceException when the reference list file could not be loaded (e.g. due to file corruption).
