### ISSUE TITLE
[Philips] Could not find file ...\Favorite.xml

### ISSUE THREAD

**Issue by sal0max** [PredatH0r/ChanSort#201]
The latest version of ChanSort gives me following error message when trying to save a Philips 55OLED803/12 (Android TV) channel list:

![grafik](https://user-images.githubusercontent.com/423373/100281634-918e6800-2f6a-11eb-9611-577dde9e8920.png)

The `Favorite.xml` file is missing, because actually it is to be found one folder higher, in `ChannelList\`, not in `ChannelList\s2channellib\`.

**Comment by laythingy59** [comment]
I've been able to get around this issue by copying the favorite.xml file from \ChannelMap_110\ChannelList\Favorite.xml into \ChannelMap_110\ChannelList\s2channellib\Favorite.xml

I don't know if this is the right thing to do, but I'm able to save my sorted list.

**Comment by sal0max** [comment]
Could you also deploy it on the tv?

**Comment by laythingy59** [comment]
Yes it depolyed to the TV just fine. What model TV do you have. 
I'm having a seperate issue detailed here https://github.com/PredatH0r/ChanSort/issues/203. Do you have these problems?

**Comment by PredatH0r** [comment]
The error about Favorite.xml is now fixed in version 2020-12-05

**Comment by sal0max** [comment]
> Yes it depolyed to the TV just fine. What model TV do you have.
> I'm having a seperate issue detailed here #203. Do you have these problems?

I've got a 55OLED803 and think I don't have your problems.

> The error about Favorite.xml is now fixed in version 2020-12-05

Thanks a lot! Works now! :)
