### ISSUE TITLE
Problems with LG OLED55GX9LA

### ISSUE THREAD

**Issue by har-kre** [PredatH0r/ChanSort#206]
Hallo,

 i have an LG OLED55GX9LA  / Web OS 5.1.1-3707 / Software 3.11.30

When I edit my channel list exported from the tv and upload it back to the tv, all channels have the number 0.
when I import my backup list it stays that way. the only way to turn this off is a factors reset, after which I can import my backup channel list again without any problems.

i add both files, ending "edit" is the list edited with chansort, the other ist the list 

which I edit with the TV and then exported

I hope this will help

best regards

[OLED55GX9LA.zip](https://github.com/PredatH0r/ChanSort/files/5648824/OLED55GX9LA.zip)

**Comment by PredatH0r** [comment]
Hi and thanks for your feedback!
Have you also tried to import the modified list in the TV right after a reset?
My current understanding is that it is a limitation of webOS5 that imports only works after a reset.

I also prepared a modified version of ChanSort (link here: https://github.com/PredatH0r/ChanSort/issues/172#issuecomment-739431292) which may or may not work without a reset.
Unfortunately I don't have a webOS 5 TV myself to test this out.

Regards,
Horst

**Comment by PredatH0r** [comment]
I took a closer look at the files you provided.
I extracted the JSON data from each file, put it in a separate file and reformatted it.
Then I ran a diff-tool to compare the 2 files.
Turns out that they are the same except for minior differences in the order of the channels. all other fields are identical.
The slightly different order can also be seen here:
![lists-side-by-side](https://user-images.githubusercontent.com/6238104/101284124-bb535480-37de-11eb-953f-d1a566574c43.PNG)

Attached is a zip with the JSON files and the diff result.
[FilesWithExtractedJsonAndDiff.zip](https://github.com/PredatH0r/ChanSort/files/5648986/FilesWithExtractedJsonAndDiff.zip)

(NOTE: channels with numbers X >= 16384 are radio channels, their actual number is X-16384)

To me this really looks like a limitation of the TVs firmware that I simply cannot import a list cleanly if there is already a list in its memory.

**Comment by har-kre** [comment]
Hallo,
ou are correct the two lists have only very few changes, I have only changed the order of two or three channels, for example. Pro7 maxx and deluxe music.
After a factory reset, I can import the original backup file several times, without any problems. The problem only occurs with the edit list from chansort. The problem also occurs when the edited list is imported directly after a factory reset.
I also wonder where the problem is, there are basically only minimal changes between the two files

**Comment by har-kre** [comment]
Hallo Horst,

 

hab gesehen du wohnst in Österreich? Kannst Du deutsch? Das würde es für mich einfacher machen.

 

Gruß

Harald

 

 

Von: Horst Beham [mailto:notifications@github.com] 
Gesendet: Sonntag, 6. Dezember 2020 15:50
An: PredatH0r/ChanSort <ChanSort@noreply.github.com>
Cc: har-kre <ha-kr@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [PredatH0r/ChanSort] Problems with LG OLED55GX9LA (#206)

 

Hi and thanks for your feedback!
Have you also tried to import the modified list in the TV right after a reset?
My current understanding is that it is a limitation of webOS5 that imports only works after a reset.

I also prepared a modified version of ChanSort (link here: #172 (comment) <https://github.com/PredatH0r/ChanSort/issues/172#issuecomment-739431292> ) which may or may not work without a reset.
Unfortunately I don't have a webOS 5 TV myself to test this out.

Regards,
Horst

**Comment by PredatH0r** [comment]
Servus Harald,
jo, I red Deitsch :)

Ich habe jetzt eine ganz neue Version hochgeladen, in der ChanSort die beiden Kennzeichen "userSelCHNo" und "userEditChNumber" bei allen Sender zurücksetzt (auf false). Es könnte an diesen Kennzeichen liegen, dass sich der Fernseher seltsam verhält beim Import.
Kannst du bitte deine mit ChanSort bearbeitet Datei mit dieser neuen Version öffnen und gleich wieder speichern?
Wäre interessant, ob sich diese Datei dann direkt nach einem Reset ohne vorherigen Sendersuchlauf importieren lässt. 

Die neue Version liegt auf https://chansort.com/ChanSort_2020-12-06_resetFlag.zip

**Comment by har-kre** [comment]
Hallo Horst,

 

ah ein Glück :)

 

also zu einen Werksreset gehört immer auch ein Sendersuchlauf, ist Teil der Einrichtung neben Sprachauswahl usw.

 

es gibt 3 Arten von Sendersuchlauf: 

1.      Mit Verschlüsselten Sendern

2.      Mit Free TV

3.      Blindscan, den mach ich immer, denn dann werden alle SAT Transponder durchsucht

 

 

Ich habe jetzt folgendes gemacht:

 

1.      Die Datei die ich mit Chansort bearbeitet habe mit der „resetFlag“ version geöffnet etwas geändert gespeichert und in den LG importiert --> die Reihenfolge der Sender stimmt nicht auf 1 muss das Erste sein 2 ist dann ZDF, es geht nun aber bei 264 mit 3 SAT los siehe Anlage das ist bei mir aber normal Platz  14

Interessant ist noch, das gleich nach dem Einschalten jeder Sender die Nr. 0 hat, hab ich schon im Forum beschrieben, nach einer Zeit (ca. 10 Sek) bekommen die Sender dann aber die Nummern und 3 Sat hat 264, der TV macht das wohl von sich aus

 

Einen Werksreset und dann nochmal die Datei eingespielt --> DAS FUNKTIONIERT !!! die Sender sind in der Reihenfolge wie ich sie mit Chansort abgespeichert habe

 

die Chansort Datei erneut eingespielt (ohne Werksreset) Stichwort reproduzierbarkeit --> funktioniert nicht mehr, nun ist wieder 264 mit 3 SAT ganz oben.

 

 

Meine mit dem TV in mühseliger fummelei erstellte Senderliste ( das ist meine Backup Datei) nach dem einspielen der Datei eingespielt, die muss ja jetzt funktionieren, wurde ja mit dem LG TV Sendermanager erstellt --> funktioniert nicht mehr, nun ist wieder 264 mit 3 SAT ganz oben.

 

Ich muss nun wieder einen Werksreset machen und dann spiele ich natürlich gleich die Liste vom LG TV Sender Manager ein, da weiß ich das die funktioniert und die kann ich auch x-mal einspielen, das klappt. 

 

 

So wie es aussieht, kann man nur nach einen Werks Reset die Chansort Datei EINMALIG ohne Probleme in den LG TV einspielen, das kannst  dann natürlich vergessen, ein Werksreset ist immer ein Akt, dauert ca. 5 bis 10 min, danach musst dann wieder alles wieder neu einrichten Bild, Ton, Apps, Netflix, usw. 

 

Harald

 

 

Von: Horst Beham [mailto:notifications@github.com] 
Gesendet: Sonntag, 6. Dezember 2020 17:52
An: PredatH0r/ChanSort <ChanSort@noreply.github.com>
Cc: har-kre <ha-kr@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [PredatH0r/ChanSort] Problems with LG OLED55GX9LA (#206)

 

Servus Harald,
jo, I red Deitsch :)

Ich habe jetzt eine ganz neue Version hochgeladen, in der ChanSort die beiden Kennzeichen "userSelCHNo" und "userEditChNumber" bei allen Sender zurücksetzt (auf false). Es könnte an diesen Kennzeichen liegen, dass sich der Fernseher seltsam verhält beim Import.
Kannst du bitte deine mit ChanSort bearbeitet Datei mit dieser neuen Version öffnen und gleich wieder speichern?
Wäre interessant, ob sich diese Datei dann direkt nach einem Reset ohne vorherigen Sendersuchlauf importieren lässt.

Die neue Version liegt auf https://chansort.com/ChanSort_2020-12-06_resetFlag.zip

**Comment by PredatH0r** [comment]
Bei meinem alten LG kann man, nachdem man den Reset gemacht und nach den Optionen für den Suchlauf gefragt wird, per Abbrechen/Zurück auf der Fernbedienung den Suchlauf überspringen und hat dann eine leere Liste.

Mir ist auch aufgefallen, dass ein anderer Benutzer heute eine neuere Version von webOS 5 hatte (5.2.0) und Software Version 3.21.10.
Womöglich hat LG da etwas behoben. Er konnte heute eine Liste importieren - ohne Reset.
Er hatte aber gezielt keine Sender gelöscht und die Funktion genutzt, damit dann alle Sender fortlaufende Nummern bekamen.

**Comment by har-kre** [comment]
Ah Ok kann sein das mein LG das auch hat mit dem überspringen, muss ich nochmal schauen. OK aber das mit der Senderliste überspringen ist ja die wenigste Arbeit, das läuft ja auch alleine. Zeit nach dem Reset brauchst halt für die Fein Einstellung von Ton, Bild, Netflix und Amazon Prime Zugangsdaten eingeben (falls das hast) und allen anderen Einstellung damit du den LG so hast wie du willst, und das hast halt immer, diese ganzen Einstellungen sind nach einem Reset weg.

 

Nach Updates hab ich gesucht, wurde kein neues gefunden. Kommt dann bestimmt für meinen TV demnächst, das letzte update ist aber auch erst 2 Wochen her.

 

Gut im Grunde passen die Sender ja nun bei mir, war halt direkt mit dem TV zu sortieren eine Wahnsinns Arbeit, hab bestimmt für alles in allem 2 Std gebraucht, das hab ich direkt nach dem TV Kauf gemacht, das muss man einmalig machen und gut ist

 

 

 

Von: Horst Beham [mailto:notifications@github.com] 
Gesendet: Sonntag, 6. Dezember 2020 19:59
An: PredatH0r/ChanSort <ChanSort@noreply.github.com>
Cc: har-kre <ha-kr@posteo.de>; Author <author@noreply.github.com>
Betreff: Re: [PredatH0r/ChanSort] Problems with LG OLED55GX9LA (#206)

 

Bei meinem alten LG kann man, nachdem man den Reset gemacht und nach den Optionen für den Suchlauf gefragt wird, per Abbrechen/Zurück auf der Fernbedienung den Suchlauf überspringen und hat dann eine leere Liste.

Mir ist auch aufgefallen, dass ein anderer Benutzer heute eine neuere Version von webOS 5 hatte (5.2.0) und Software Version 3.21.10.
Womöglich hat LG da etwas behoben. Er konnte heute eine Liste importieren - ohne Reset.
Er hatte aber gezielt keine Sender gelöscht und die Funktion genutzt, damit dann alle Sender fortlaufende Nummern bekamen.

**Comment by PredatH0r** [comment]
Mit aktueller WebOS 5 Firmware sind seit längerer Zeit keine Probleme mehr gemeldet worden.
Ich vermute dass LG hier nachgebessert hat.
