### ISSUE TITLE
no channels visible in ChanSort

### ISSUE THREAD

**Issue by AndyBauer119** [PredatH0r/ChanSort#209]
I have the problem that no channels are visible in ChanSort
![Chansort](https://user-images.githubusercontent.com/76034121/102184176-54553000-3eaf-11eb-928d-4fc89e97a6fa.jpg)
, although the channels are all present in the file. If I open ChanSort on a USB stick with the same TLL file on another computer, all channels are displayed. What can be the problem here?

**Comment by PredatH0r** [comment]
Can you please mail me your channel list or attach it to this thread?
But the problem might be something unrelated to your list. It looks like the columns in the table are so extremely wide that the right-aligned numbers are only visible when you scroll horizontally.

Please close ChanSort, open a Windows Explorer, enter "%LocalAppData%" in the top line and then delete the ChanSort folder there. This is where the user settings are stored. When you start ChanSort the next time, it should all be normal again.

**Comment by AndyBauer119** [comment]
Thanks for your help. Your hint to delete the ChanSort folder in the %LoacalAppData% solved my problem.
The original channel list: 
[GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/5721161/GlobalClone00001.zip)
