### ISSUE TITLE
Philips channels from Samsung TV ?

### ISSUE THREAD

**Issue by ju22re** [PredatH0r/ChanSort#212]
Hi,

currently I do have a problem with my Philips TV.
For some reason I can't receive all sky-channels, even not after after factory reset and a new channel search....
My other TV (Samsung) receives all the required channels.
My question:
Can I somehow import that Samsung channels into the Philips TV by using ChanSort ?
(The Samsung generates only one .scm file)

cheers

ju22re

**Comment by ju22re** [comment]
Hi,

OK, problem solved...
I installed the channels in the wrong way :-(
(I choosed "limited to germany" instaed of "all channels")

The only remaining problem is:
How can I transfer the sorted channels from Samsung TV (or from Philips 65PUS6754)
to Philips 32PFS6401....? (Seems that ChanSort doesn't support Philips 32PFSxxxx)

Jürgen

**Comment by PredatH0r** [comment]
Philips used several completely different file formats over the time, plus some variations of those. 
I don't know exactly what kind of format your 32PFSxxxx is using. You can send me the file and I will take a look.
I know that there are a couple Philips formats that I can't support at the moment, but with more sample files and information that could change.

**Comment by PredatH0r** [comment]
i just remembered ... some older Philips models exported some files to the stick that were visible in Windows Explorer and some additional files (including the channel list) with a "hidden" file attribute.
In Windows Explorer you need to click on "View" and select the "Hidden elements" (Ansicht / Ausgeblendete Elemente).
In case your TV exported a file like CM_T923E_LA.BIN (visible) you will then also see a CM_T923E_LA.xml (invisible).

**Comment by ju22re** [comment]
...attached a file from the Philips 32PFSxxxx.
I just removed the syslogo.tar (~50MB)

Jürgen


[PhilipsChannelMaps.zip](https://github.com/PredatH0r/ChanSort/files/5751639/PhilipsChannelMaps.zip)

**Comment by ju22re** [comment]
wrong button :-)

**Comment by PredatH0r** [comment]
oh right, the "ChannelMap_45" format. totally different to all the others.
The weird thing about it is that it contains everything twice. One time inside a "tv.db" SQLite database file and then again inside binary files in channellib and s2channellib. I'm not entirely sure if both or just one (and which one) need to be updated.
I'll see what I can do

**Comment by ju22re** [comment]
...do you have any news regarding the "ChannelMap_45" format ?

**Comment by PredatH0r** [comment]
I have a version of ChanSort which can read and write the Map45 format, but it does not update the tv.db file yet.
I am not sure if the current version is good enough or if that tv.db must also be updated by ChanSort to match the program numbers in the other files. My guess is that the EPG could show wrong program numbers, but maybe the TV automatically updates the tv.db file.

If you want, you can give it a try: https://chansort.com/ChanSort_2021-01-13.zip

**Comment by ju22re** [comment]
unfortunately it doesn't work.

I just exported a new channel list from the tv, modified some channels and tried to import it again.
There was just an error shown on the tv: "there is an error. list can't be imported"

**Comment by PredatH0r** [comment]
Thanks for your time and feedback!
I'll keep working on it and will keep you posted here. I hope that I can get another update ready over the weekend.

**Comment by PredatH0r** [comment]
Next attempt: https://chansort.com/ChanSort_2021-01-15.zip

This version also updates the tv.db file and calculates the correct checksum for it. The bad checksum was probably the reason why it failed last time.

**Comment by ju22re** [comment]
well, allthough there was an error shown on the tv (when importing the channel list from usb)
"error. the list was not exchanged",
the new channel list was copied to the tv.

so, everything is working fine. many thanks for your effort.
