### ISSUE TITLE
Add cleaner tivùsat channel list

### ISSUE THREAD

**Issue by Double-A-92** [PredatH0r/ChanSort#216]
Hi, 

I created a clean list of Italian tivùsat channels based on the official "Easy HD" [list](https://canalisat.altervista.org/tivusat.php). 
What is the proper way to propose that as a new template? The currently existing one also includes tons of other channels on Hotbird which Italian people probably would not really want (and makes combinations with other lists hard).

[it_tivusat_EasyHD.txt](https://github.com/PredatH0r/ChanSort/files/5759548/it_tivusat_EasyHD.txt)

Also here is a list of other free Italian channels which are missing from the official tivùsat list. Needs more work though on how to reasonably merge those lists. 
[it_hotbird130E_FTA.txt](https://github.com/PredatH0r/ChanSort/files/5759639/it_hotbird130E_FTA.txt)

**Comment by PredatH0r** [comment]
These refrence lists are simple text files and can be edited with any text editor - or even Excel.
Columns are separated with a semicolon.
Column 1: program number
Column 2: channel name
Column 3: ONID-TSID-SID (original network ID, transport stream ID, service ID) which identifies a channel uniquely, unlike the name.

When applying a reference list, ChanSort first tries to match channels from your actual list and the reference list based on the same ONID-TSID-SID. If it doesn't find a match, it tries to find a match by name, which may or may not be unique and therefore less reliable. The latter also fails if a channel is officially renamed - like "ARD" became "Das Erste".

**Comment by JonnyTech** [comment]
How do I use this? I selected it and got a list but the telly then shows the channel names with no signal on all.

**Comment by PredatH0r** [comment]
First, you need to go in your TV's menu and export its current channel list to USB.
Then you connect that USB stick to your PC and open the channel list with ChanSort.
You are asked how you would like to edit your list. Select the option to apply the same order as in another list.
Now you can select one of the reference lists that come shipped with ChanSort, l ike the it_tivusat_EasyHD.txt above, or any other channel list that can be read by ChanSort (e.g. from another TV you already ordered).
Then save the list, connect the USB stick to your TV and import the list.

**Comment by JonnyTech** [comment]
That was exactly what I had done. I finally resorted to doing a factory reset on the telly and it now seeems to be working. Strange. Thanks for your reply, it helped to know that I was doing it correctly.

**Comment by PredatH0r** [comment]
The it_hotbird130E_tivusat reference lists are included in ChanSort for some time now
