### ISSUE TITLE
Editing Favorite List on PC

### ISSUE THREAD

**Issue by breashy** [PredatH0r/ChanSort#218]
Hey,
i downloaded the app and it was very useful to edit the tv channels for the LG TV with OS 5.2,
however, i am not able to edit/make any favorite list of channels form the pc,
ive tried to make a list on tv and export it back to the pc, but still i cant see the list nor edit it

**Comment by PredatH0r** [comment]
ChanSort currently does not support favorite lists for webOS 5 because I have not been able to identify if and where that information is stored in the file.
If you can send me a file with channels added to Fav1-Fav8 and let me know, which channels these are, I can probably find out how to add support for it.

**Comment by breashy** [comment]
Hey,
Thanks for your reply,
Eve edited the favourite name on the tv instead of favourite 1 renamed to News, Fav 2 Drama, and so on
However I am attaching for your the file and below table for your reference

Favourite Original 
Number	Renamed to	Channel Included
1	News	12Arabia
2	Drama	7SPIRITS TV
3	Movies	7 STARS TV

**Comment by PredatH0r** [comment]
i assume you attached your list your email reply. unfortunately github.com drops the attachments and only adds the message to the thread.
can you please send me your list directly to horst @ beham . biz ?
Thanks!

**Comment by mettyec** [comment]
Thanks. I changed the order of the channels in alphabetical order. Works perfectly on LG 24TL510V-PZ. Ignored 4K channels.

**Comment by mettyec** [comment]
Here is .TTL for LG 24TL510V-PZ
[GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/5912434/GlobalClone00001.zip)

**Comment by breashy** [comment]
Thanks
Will give ut a try


Best Regards,
Ali El Breashy

**Comment by mettyec** [comment]
It is useful to see the result of the alphabetical arrangement.
[GlobalClone00001SortNew.zip](https://github.com/PredatH0r/ChanSort/files/5912771/GlobalClone00001SortNew.zip)

**Comment by PredatH0r** [comment]
The WebOS 5 file format does not support information about favorite lists.
