### ISSUE TITLE
Reference Lists Files for m3u files do not work

### ISSUE THREAD

**Issue by Super3003** [PredatH0r/ChanSort#220]
Lets take an example m3u file (but it is the same for any m3u file i tried)
http://siptv.app/lists/example.m3u

I want to use some kind of reference file to sort m3u files. Now I have tried the following:

1. using .txt reference files:
If I sort 3 channels from this list, do a litte re-order and save it as reference list file. 
When I now try to load the example.m3u and choose "Order the channels in the same way as in a reference list", and select the reference txt file I just created it shows that the reference list is OK, but nothing is loaded to the sorted channels when I press "Apply", just nothing happens.

2. using m3u reference files
Since ChanSort can now use files of the same type (m3u) to do the sorting:
If I sort 3 channels from this list, do a litte re-order and save it now as m3u file. 
When I now try to load the example.m3u and choose "Order the channels in the same way as in a reference list", and select the "reference" m3u file I just created I have 2 options:

2.1. If "Automatically reorder all lists..." is clicked, there are files appearing in the "Sorted Channels" box, but these are the wrong channels. These are just the top 3 channels from "Original Channels" box. 
The number 3 comes from the number of channels I previously selected, and can vary accordingly.

2.2 or if "Advanced reordering" is selected, again, nothing happens as in 1, when "Apply" is pressed.

I found no way to have any kind of reference file to sort m3u files.
I would be happy if somebody would have a look at this.
Thank you

**Comment by PredatH0r** [comment]
This is now fixed in version 2021-01-24
