### ISSUE TITLE
Channel names umlaut not shown correct - Phillips FW TPM 171.

### ISSUE THREAD

**Issue by Janpopan** [PredatH0r/ChanSort#221]
Example

is
BR Fernsehen S�d HD

should

BR Fernsehen Süd HD

The XML hex mapping hooks like ISO-8859-1 

`<Setup SatelliteName="0x41 0x00 0x53 0x00 0x54 0x00 0x52 0x00 0x41 0x00 0x20 0x00 0x31 0x00 0x39 0x00 0x2E 0x00 0x32 0x00 0x45 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00" ChannelNumber="32" ChannelName="0x42 0x00 0x52 0x00 0x20 0x00 0x46 0x00 0x65 0x00 0x72 0x00 0x6E 0x00 0x73 0x00 0x65 0x00 0x68 0x00 0x65 0x00 0x6E 0x00 0x20 0x00 0x53 0x00 0xFC 0x00 0x64 0x00 0x20 0x00 0x48 0x00 0x44 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00" ChannelLock="0" UserModifiedName="0" LogoID="1601" UserModifiedLogo="0" LogoLock="0" UserHidden="0" FavoriteNumber="0" Scrambled="0"></Setup>
<Broadcast UniqueID="324" ChannelType="3" Onid="1" Tsid="1025" Sid="32" Frequency="11582" Modulation="8-VSB" ServiceType="1" SymbolRate="22000" LNBNumber="1" Polarization="1" SystemHidden="0"></Broadcast>
</Channel>`

**Comment by PredatH0r** [comment]
Can you send me your Repair or PhilipsChannelMaps folder please so I can take a look?
In your case the hex numbers are 16-bit little endian unicode characters and the 0xFC 0x00 in there should be the "ü".

But all other files I have seen so far have every 2nd byte in the hex data 0x00 and the bytes inbetween need to be interpreted as utf-8 to properly show umlauts and other special characters.

So at the moment, I don't know how to detect which type of encoding is used.

**Comment by PredatH0r** [comment]
never mind... my bad. it's all clear now and you were right. this will be fixed in the release coming out later today.

**Comment by Janpopan** [comment]
It works with the new ChanSort_2021-01-17 build - thanks!
