### ISSUE TITLE
Import XLS to Chansort

### ISSUE THREAD

**Issue by Deezell** [PredatH0r/ChanSort#223]
I have a 2017 Samsung Q series. I'm looking to make a favourites list with a mix of DVBT and DVBS, Terrestrial and Satellite.
 Is there any method to do this. If I export the lists to Xcel, and edit, is it possible to import a mixed xls list. I do not see a method to cut and paste on Chansort.
 It takes 11 button presses on the Samsung remote to go from a DVBS tuner to a DVBT tuner,and this before you can then select a channel using the remote. Favourite lists do not build over two tuners. Occasionally a most watched list in the recent channels smart bar displays a channel from DVBS while watching DVBT, so a quick change of tuner is possible. Any method of changing tuner quickly, or listing a DVBS channel and a DVBT channel on a favourite guide would be a huge step,

**Comment by PredatH0r** [comment]
Samsung does not support mixing channels from different input sources.
Each source is managed in its own separate list file inside the .scm/.zip.

Some other manufacturers at least allow favorites lists to mix channels from sources, but not Samsung.

**Comment by Deezell** [comment]
I wonder which manufactures allow a mixed favourites list. I will be purchasing another 55 smart TV, I am considering Sony or TCL Android, possibly Panasonic.

**Comment by PredatH0r** [comment]
From what I've seen in the various channel list file formats, mixed lists are supported by
- Grundig (not 100% sure, but possible)
- Hisense (2017 and later models with a servicelist.db file)
- Philips
- Sony (only Android based models)

For sure not supported by:
- Samsung
- LG (webOS 5 doesn't export/import any information about favorites, so I can't tell if/how they are supported on the TV)

Not sure about the latest models from Panasonic and Toshiba. The ones I know don't support it.

**Comment by Deezell** [comment]
That is really useful information. Sales staff have no clue, and demo sets are all on HDMI or network feed, no mixed air/sat feed to test. Sony KD90 series Android or TCL C815 Android  Qled,  if it is similar to Hisense, it can probably do mixed. Thanks for the info.
