### ISSUE TITLE
Panasonic HX940Series (2020) - System.InvalidCastException

### ISSUE THREAD

**Issue by Seddi75** [PredatH0r/ChanSort#225]
Im not able to load svl.bin or svl.db from a Panasonic TX-43HXG944 with actual firmware. Doesnt matter if I export via Menu (svl.bin) or go over hotel.pwd to get the svl.db. Maybe they changed the file format for the newer models. Anyone else tried with one of the 2020 models ?

I attach both svl.bin and db, maybe someone will take a look into it.

[PanasonicHX940series.zip](https://github.com/PredatH0r/ChanSort/files/5984486/PanasonicHX940series.zip)

**Comment by PredatH0r** [comment]
Channel 414, "BVN TV") in your list refers to a non-existing transponder, so ChanSort fails to determine the frequency and produces an error.

I made a modification to ChanSort to allow reading your file, but I strongly recommend that you run a new channel search on your TV, export the data again and try opening that file. I assume a new search will clear the invalid channel from the list.
You can find the updated version here: https://chansort.com/ChanSort_2021-02-16.zip

**Comment by Seddi75** [comment]
Hmm OK ... was a clean scan yesterday, but I will try a second scan this evening. Thx for the fast response, I will try it.

**Comment by PredatH0r** [comment]
In that case it's probably not worth running a new scan, as it will likely create the same result.
Editing your existing file should be sufficient then. I'm curious though if you can actually watch the channel with number 414.

**Comment by Seddi75** [comment]
> I'm curious though if you can actually watch the channel with number 414.
Will try it this evening.
