### ISSUE TITLE
Grundig 42 GHB 5742

### ISSUE THREAD

**Issue by dev-9** [PredatH0r/ChanSort#227]
Hi all,

I try to use chansort with the Grundig 42 GHB 5742 tv-list. The export from the TV provides an directory called "My_Channellist" and three files, but only the "dvbs_config.xml" is interessing for me.

As I understand the ChanSort.Loader.Grundig might support some Grundig channel lists, but unfortunately not this one.
I get the message "No module to read/write ..." with a System.NullReference.Exception in the ChanSort.Loader.Grundig

![error](https://user-images.githubusercontent.com/80591719/111036462-985cc000-841f-11eb-83b1-4c4debd22c87.JPG)

Can you please give me a tip how I can try to proceed:
- should I try to modify and build the ChanSort.Loader.Grundig for the mapping I can find out in the xml?
- should I try to modiffy the dvbs_config.xml to a matching format? Can anybody please send me the expected format?
- any other ideas?

Best reards,
Jens

**Comment by PredatH0r** [comment]
Can you please send me your file to horst@beham.biz?
It looks like a bug in ChanSort that I should be able to fix easily when I can reproduce the problem.

**Comment by dev-9** [comment]
Thank you, I have send you the file. Hopefully we find the cause.

**Comment by PredatH0r** [comment]
Uploaded a fixed version to https://chansort.com/ChanSort_2021-03-13.zip

This is an alpha-version where I am currently reworking the whole reference-list system. The "automatically reorder all lists"-Option does not work here, the advanced / manual selection of a particular sub-lists should work.

The cause of the error was the dvbt_config.xml file, which did not have a \<channels\> element inside the \<Digital\> element

**Comment by dev-9** [comment]
Thanks a lot - it works. Makes sense, because I'm only using DVB-S. A work around with the stable version is also to delete the dvbt_config.xml and dvbc_config.xml (as I now understand)
