### ISSUE TITLE
Update check on start still doesn't work with ChanSort_2021-03-16_1600.zip

### ISSUE THREAD

**Issue by Lutebe** [PredatH0r/ChanSort#229]
![ChanSort 2021-03-16](https://user-images.githubusercontent.com/80776580/111343355-a1e26400-867b-11eb-858c-7269ca9862cc.png)

**Comment by PredatH0r** [comment]
Thanks.
I should not have rounded 15:58 up to 16:00 and forgot that I should use UTC and not CET timestamps.
Renamed the 1600 package to 1458 and now it works as intended.
