### ISSUE TITLE
How can I add a new channel or edit an existig one in my list 

### ISSUE THREAD

**Issue by Willi77930** [PredatH0r/ChanSort#230]

**Comment by PredatH0r** [comment]
It is a bit unclear what you are trying to achieve.

ChanSort does not support adding new channels to the TV that were not found when you ran the channel search on the TV.
Neither does it allow editing of the tuner parameters. 
Most TVs need a lot more than just these numbers to properly tune a channel and many channel list formats don't even provide information about tuner settings.

If you mean adding a channel to a favorites list or to the main list (when you started with an empty one), all you need to do is select "Edit option: after" and then double-click a channel in the right list.

**Comment by PredatH0r** [comment]
Unfortunately that's not possible with ChanSort.
But what you can do with ChanSort is to keep your current list as a "reference list" (save the file somewhere), run a new scan on your TV, export that file to USB and open it in ChanSort. Then select the option to "copy order from another file" and select your old file. 
You should have the same order now and can adjust "Russia Today" in case it hasn't been put at the right position

**Comment by Willi77930** [comment]
Thank you for your time and an solution. Jeep healthy.

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
