### ISSUE TITLE
Opening Samsung-ZIP: Channel list stays empty 

### ISSUE THREAD

**Issue by Stuetti** [PredatH0r/ChanSort#231]
Device: Samsung GQ65Q80TGTXZG
[Channel_list_T-NKMDEUC-1497.0.zip](https://github.com/PredatH0r/ChanSort/files/6281343/Channel_list_T-NKMDEUC-1497.0.zip)
USB stick is formated FAT32

I tried to open the channel list from my Samsung tv, but the list in ChanSort stays empty. It was working once, but after rescanning satelite channels on TV and exporting the list again, nothing happens in ChanSort any more. I tried it multiple times.

Is there a logging possibility in ChanSort?

**Comment by PredatH0r** [comment]
Thanks for your report.
This is now fixed in https://github.com/PredatH0r/ChanSort/releases/tag/v2021-04-10

**Comment by Stuetti** [comment]
Tested and works. Thanks.
