### ISSUE TITLE
does not work on new Samsung Neo QLED 2021

### ISSUE THREAD

**Issue by abhatop** [PredatH0r/ChanSort#234]
short error description:

- export channel list to usb
- edit with chanSort
- Saved back to USB
- tried to upload to Samsung NEO QLED
- error message: channel list not supported

any advise is much appreciated

**Comment by PredatH0r** [comment]
Can you please send me your unmodified (*.bak) and modified (*.zip) channel list?

**Comment by abhatop** [comment]
Hi,

sure...please find attached.

br
Manuel


Am Di., 20. Apr. 2021 um 08:34 Uhr schrieb Horst Beham <
***@***.***>:

**Comment by abhatop** [comment]
sorry - thats me again - I overlooked what you really asked for ;-)
the first file i sent you was an direct export from the tv - unmodified.
attached you will find now what you asked for ;-)
br
manuel


Am Di., 20. Apr. 2021 um 10:12 Uhr schrieb ABhATOP ***@***.***>:

**Comment by PredatH0r** [comment]
Hi Manuel,
unfortunately attachments get lost when you reply to a github notification email.
You can either upload files on the github website, or send it to my regular email address horst @ beham . biz.
Thanks!

**Comment by abhatop** [comment]
in your inbox ;-)

**Comment by PredatH0r** [comment]
This turned out to be a version mismatch between the file (version is part of the filename) and the TV's firmware.
