### ISSUE TITLE
svl1.db und svl2.db zu einer Datei (svl1_2.db) zusammenführen

### ISSUE THREAD

**Issue by jbstm** [PredatH0r/ChanSort#235]
Hallo,

ich möchte 2 Senderlisten zusammenführen.
Beide Listen (svl1.db und svl2.db) sind aus einer Originalliste (svl.db) entstanden.

svl1.db enthält die ersten 10 Einträge von svl.db und
svl2.db enthält die letzten 10 Einträge von svl.db.

Beim 'Speichern unter' wurde jeweils die Aktion 'Sender löschen' gewählt, so dass in svl1.db und svl2.db jeweils nur 10 Sender vorliegen (also auch keine verstecken).

Meine Frage:
Wie kann ich svl1.db und svl2.db zu einer Datei (svl1_2.db) zusammenführen ?

Was heißt eigentlich svl (Sender????Liste) ?

Leider lässt sich die .db nicht mit SQLite öffnen, da mir das Passwort für die SQL Cipher-Verschlüsselung nicht bekannt ist. Was tun ?

Über eine Rückmeldung würde ich mich freuen.

jbstm

**Comment by PredatH0r** [comment]
Sorry für die späte Antwort, irgendwie habe ich deine Meldung leider übersehen.

Ich vermute "SVL" steht für Service List. TV-, Radio- und Datensender werden im DVB Fachjargon als "Services" bezeichnet.
Panasonic hat seine eigene Verschlüsselung für svl.db und svl.bin Dateien bzw. fügt da noch ein paar Daten davor und dahinter an. Wenn man die Liste mit ChanSort öffnet, wird eine temporäre unverschlüsselte .db Datei im selben Verzeichnis angelegt. Die kann man mit einem SQLite Browser ansehen.

Zusammenführen geht nur über den Umweg mit einer 3. Datei, in der noch alle Sender vorhanden sind.
Dann kann man nacheinander die 1. und 2. Datei als Referenzliste ("Vorlagendatei") öffnen und auswählen, ab welcher Programmnummer die jeweilige Teilliste angewandt werden soll.
