### ISSUE TITLE
Visual c++ no longer avaible

### ISSUE THREAD

**Issue by bedo1987** [PredatH0r/ChanSort#236]
Hi,
I wanted to try you program for my Samsung TV, but in order to import my .zip file I need Visual C++ 2010 x86 to be installed in my pc (latest w10).
Microsft website has no longer the setup files
https://www.microsoft.com/en-us/download/details.aspx?id=5555
Can you help me find out how to install the needed package?
Thanks
Alessio

**Comment by PredatH0r** [comment]
wow... thanks for the info!
Just a few weeks ago I downloaded it from the Microsoft page. Looks like all links that Google returns are dead-ends now.

I uploaded a copy of it to https://chansort.com/vc2010redist_x86.exe

Going forward I am investigating ways to get rid of that dependency for ChanSort.

**Comment by PredatH0r** [comment]
Recent versions of ChanSort no longer need the VC++ 2010 redist.
For older versions, here is Microsoft's new download link: https://www.microsoft.com/en-us/download/details.aspx?id=26999
