### ISSUE TITLE
Net Framework Dependency

### ISSUE THREAD

**Issue by spinalgr1990** [PredatH0r/ChanSort#238]
Is it possible to remove Net Framework 4.8 Dependency ?

My pc only can runs only Net Framework  version 4.6

**Comment by PredatH0r** [comment]
Unfortunately not.
ChanSort uses functions that are only available in 4.7 and later (high-DPI support for monitors with display scaling other than 100%/96dpi) and uses 3rd party libraries that are designed for 4.8 (NuGet packages for Sqlite database access).
