### ISSUE TITLE
Leere Sendernamen

### ISSUE THREAD

**Issue by NotEriic** [PredatH0r/ChanSort#239]
Servus mein lieber,
seit kurzem sehe ich in ChanSort keinerlei Sendernamen mehr.
Ich muss erst auf "Sender umbenennen" drücken dann werden die Namen sichtbar.

Liegt das nur an mir oder ist das ein Bug?

Die servicelist.db kann ich dir gerne zur verfügung stellen.

Liebe Grüße
NotEriic

**Comment by PredatH0r** [comment]
Hallo NotEriic,

kann es eventuell sein, dass die Spalten bei dir derart breit sind, dass man überhaupt nur noch eine einzige in der Tabelle sieht?
Dieses Phänomän tritt auf, wenn man in Windows eine Anzeigeskalierung ungleich 100% eingestellt hat. Dann werden bei jedem Programmstart die gespeicherten Spaltenbreiten immer weiter hochgerechnet.

In der aktuellen Programmversion ist dazu im Menü eine Funktion für "Standardoptionen wiederherstellen" eingebaut. Die löscht einfach die ChanSort Config-Datei in %LocalAppData%\ChanSort. Diese Programmversion rechnet auch die Spaltenbreiten nicht mehr weiter hoch, ist aber auch noch nicht perfekt was die Anzeigeskalierung betrifft.

LG,
Horst

**Comment by PredatH0r** [comment]
Hallo NotEriic,
hat sich das Problem mittlerweile gelöst oder besteht es immer noch?
