### ISSUE TITLE
Humax C1 DB File Not Supported

### ISSUE THREAD

**Issue by mahdose** [PredatH0r/ChanSort#240]
I have a customized provider's Humax C1 and Channel list is exported as .db file and I get error when I load it. Any ideas?

**Comment by PredatH0r** [comment]
Can you send me your file please?
.db is a very generic file extension and used for all kind of incompatible things.
Panasonic, Hisense and Toshiba store their lists as SQLite database files with the extension .db - but all have entirely different internal structures.
I guess Humax also uses a SQLite database, but with yet another internal structure.
Some TVs/receivers save files with a .db file extension but contain binary data that can't be understood at all.

**Comment by PredatH0r** [comment]
Unfortunately this file is compressed/encrypted in an unknown way, which makes it impossible for me to add support for it.
