### ISSUE TITLE
Philips 803

### ISSUE THREAD

**Issue by Buggitheone** [PredatH0r/ChanSort#245]
Hallo zusammen,

ich würde eine Antwort auf Deutsch bevorzugen alternativ aber auch auf Englisch, schreibe deswegen in beiden Sprachen.

Ich benutze den TV Philips 803. Habe ganz normal, wie in der Anleitung beschrieben, den USB Stick in den TV - Kopiert; in den PC und wollte dann das Ganze hinzufügen.

Kriege ständig diese Fehlermeldung. Tipps ?
![issue](https://user-images.githubusercontent.com/87474409/125771073-277c0626-12c3-4167-a441-69c9574a9e05.png)

Hello everybody,

I would prefer an answer in German, but also in English, so I write in both languages.

I use the Philips 803 TV. As described in the instructions, I copied the USB stick into the TV as normal; into the PC and then wanted to add the whole thing.

Keep getting this error message. Tips?

**Comment by PredatH0r** [comment]
Kannst du bitte ein .zip des ChannelList-Ordners hier anfügen?
Es sieht so aus, als ob ChanSort die Datei s2channellib\\DVBS.xml nicht einlesen kann. Den genauen Grund kann ich nur sagen, wenn ich sehe, was in dieser Datei enthalten ist. Um die Liste zu laden benötige ich aber auch alle anderen Dateien in ChannelList\

**Comment by Buggitheone** [comment]
[ChannelList.zip](https://github.com/PredatH0r/ChanSort/files/6822450/ChannelList.zip)
 
und danke für die schnelle Antwort !

**Comment by PredatH0r** [comment]
Die DVBS.xml Datei ist leider beschädigt und enthält zum Teil Datenmüll, deshalb kann sie nicht verarbeitet werden.
(Müll beginn bei Zeile 1452 der Datei)
![grafik](https://user-images.githubusercontent.com/6238104/125775786-9fbbb068-1859-4938-9ac7-e35b95e18fed.png)

Unlesbar wird es dann bei Zeile 5823, die statt mit "\<Ch" mit NUL NUL beginnt 
![grafik](https://user-images.githubusercontent.com/6238104/125776163-a7a504a7-4388-4be7-89e6-37fde82d82ca.png)

Übliche Ursache ist ein USB-Stick, der mit NTFS formatiert ist, was bei Fernsehern öfters zu Problemen führt.
Versuche es bitte mit einem Stick, der FAT32 (nicht exFAT oder NTFS) formatiert ist und <= 16GB groß ist.
Manchmal hilft es auch, einfach nur einen anderen Stick zu verwenden oder ihn bloß neu zu formatieren.

Es kommt aber auch gelegentlich vor, dass bereits die Daten im Speicher des Fernsehers durcheinander sind. Das kann z.B. nach einem Firmwareupdate passieren. Hier hilft dann nur ein Zurücksetzen auf Werkseinstellungen, neuer Sendersuchlauf und erneut exportieren.

**Comment by Buggitheone** [comment]
Habe genau das Formatierungsformat gewählt und einen 2 GB Stick genommen. Ohne Erfolg.

Habe nun einfach einen komplett anderen genommen. Nochmal formatiert auf FAT32. Eingesteckt, Kopiert, in den Rechner -> Es funktioniert.

Vielen Dank für die schnelle Hilfe !
