### ISSUE TITLE
Sortierung nach Pr# Nummern funktioniert nicht

### ISSUE THREAD

**Issue by Stonebiter** [PredatH0r/ChanSort#246]
Hallo Horst!
Zuerst einmal vielen Dank für ChanSort! Das ist wirklich eine tolle App!!

Meine Frage / Fehlbedienung oder Bug?:
Wenn ich eine von Samsung TV Q-Serie erstellte .zip-Datei in Chansort öffne, sehe ich auf der linken Seite "Sortierte Sender" und auf der rechten Seite "Alle Sender".
Nun klicke ich zuerst auf auf "Fav A" und dann im HauptMenü auf "Bearbeiten" und wähle "Favoriten nach Pr# nummerieren.
Die Reihenfolge der Liste "Sortierte Sender" ändert sich. Die Nummerierung ist nicht mehr fortlaufend.
Die Nummern, die jetzt angezeigt werden, sind die Nummern, die man auf der Fernbedienung eingeben muss, um den entspr. Sender anzuschauen.
Beispiel:
Eurosport steht in der Channel-List auf Position 14. Es hat aber die Programm-Nummer 47.
Ich möchte aber, dass Eurosport die Programmnummer 14 bekommt, damit ich mit der TV-Fernbedienung Eurosport mit der Nummer 14 aufrufen kann.
Wenn ich nun die Programm-Nummer in der Liste "Sortierte Sender" manuell eintrage und dann die Liste speichere, dann schließe und dann wieder öffne, steht Eurosport zwar auf Position 14. Wähle ich dann aber über "Bearbeiten/Favoriten nach Pr# nummerieren", hat Eurosport immer noch die Programmnummer 47. Spiele ich diese Liste zurück auf das TV, muss ich dort auf der Fernbedienung "47" eingeben (statt der gewünschten 14), um Eurosport anzuschauen.

Was mache ich falsch? Oder könnte es sich doch um einen Bug oder ähnliches handeln?
Herzliche Grüße aus dem Norden
Uwe

**Comment by PredatH0r** [comment]
Hallo Uwe!

 

Bei den aktuellen TV Modellen ist es so, dass die Sender in der Hauptliste und den einzelnen Favoritenlisten unterschiedliche Nummern haben können.

Es kommt dann also darauf an, welche „Liste“ man am Fernseher gerade ausgewählt hat.

Selber besitze ich keinen aktuellen Samsung Fernseher, kann also keine 100% genaue Anleitung dafür geben. Üblicherweise gibt es aber eine „Liste“-Taste auf der Fernbedienung und man kann dann z.B. zwischen „Astra 19.2“ oder „Favoriten 1“ o.ä. umschalten.

 

Persönlich verwende ich auf meinem Fernseher keine Favoritenlisten. Ich sortiere nur die Hauptliste („Sat“ bzw. „Astra 19.2“).

Die Funktion „Nach Pr# sortieren“ ist dafür gedacht, die Programmnummern aus der Hauptliste in die gerade geöffnete Favoritenliste zu kopieren um sie danach anzupassen..

 

In der linken Liste („sortierte Sender“) sollte man in der Regel die Spaltensortierung auf der Spalte „Neue Pr#“ belassen (rot markiert). Man kann das zwar durch Klick auf die Spaltenüberschriften auf andere Spalten ändern, aber danach werden einige Funktionen deaktiviert, weil Umreihen nur Sinn ergibt, wenn die angezeigte Tabellensortierung nach den Programmnummern erfolgt.



 

Man kann die Nummern auf viele verschiedene Arten ändern in ChanSort.

Eine Möglichkeit ist wie hier z.B. direkt dort wo „3“ vor RTL HD steht, eine andere Zahl hineinzuschreiben. Oder die Zeile auszuwählen und dann den grünen Pfeil rauf/runter zu klicken (was nur möglich ist, wenn die Anzeige nach der „Neue Pos#“-Spalte sortiert ist).

 

Grundsätzlich sollte dann am Fernseher immer genau die Nummer auf der Fernbedienung eingegeben werden, die links vor dem Sendernamen angezeigt wird – vorausgesetzt man ist in der richtigen Liste (DVB-C oder Fav1 – Fav5)

 

From: Stonebiter ***@***.***> 
Sent: Montag, 19. Juli 2021 20:33
To: PredatH0r/ChanSort ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PredatH0r/ChanSort] Sortierung nach Pr# Nummern funktioniert nicht (#246)

 

Hallo Horst!
Zuerst einmal vielen Dank für ChanSort! Das ist wirklich eine tolle App!!

Meine Frage / Fehlbedienung oder Bug?:
Wenn ich eine von Samsung TV Q-Serie erstellte .zip-Datei in Chansort öffne, sehe ich auf der linken Seite "Sortierte Sender" und auf der rechten Seite "Alle Sender".
Nun klicke ich zuerst auf auf "Fav A" und dann im HauptMenü auf "Bearbeiten" und wähle "Favoriten nach Pr# nummerieren.
Die Reihenfolge der Liste "Sortierte Sender" ändert sich. Die Nummerierung ist nicht mehr fortlaufend.
Die Nummern, die jetzt angezeigt werden, sind die Nummern, die man auf der Fernbedienung eingeben muss, um den entspr. Sender anzuschauen.
Beispiel:
Eurosport steht in der Channel-List auf Position 14. Es hat aber die Programm-Nummer 47.
Ich möchte aber, dass Eurosport die Programmnummer 14 bekommt, damit ich mit der TV-Fernbedienung Eurosport mit der Nummer 14 aufrufen kann.
Wenn ich nun die Programm-Nummer in der Liste "Sortierte Sender" manuell eintrage und dann die Liste speichere, dann schließe und dann wieder öffne, steht Eurosport zwar auf Position 14. Wähle ich dann aber über "Bearbeiten/Favoriten nach Pr# nummerieren", hat Eurosport immer noch die Programmnummer 47. Spiele ich diese Liste zurück auf das TV, muss ich dort auf der Fernbedienung "47" eingeben (statt der gewünschten 14), um Eurosport anzuschauen.

Was mache ich falsch? Oder könnte es sich doch um einen Bug oder ähnliches handeln?
Herzliche Grüße aus dem Norden
Uwe

**Comment by Stonebiter** [comment]
Guten Morgen Horst,

vielen Dank für deine schnelle Antwort!
Ich werde deiner Beschreibung gemäß die Listen ganz neu aufbauen und dann in den TV unserer Freunde importieren.
Bei unserem TV (Samsung Q-Serie) hat das bereits jetzt fehlerfrei funktioniert.
Deshalb bin ich optimistisch, dass das dann auch bei unseren Freunden klappen wird.
Ich hoffe, dass ich das diese Woche schaffe. Muss ein paar km dorthin fahren.
=> Ich werde dann auf jeden Fall sofort hier berichten, damit der Thread anschl. abgeschlossen werden kann.

Beste Grüße
Uwe

**Comment by Stonebiter** [comment]
Es hat alles geklappt! Alle Sender haben jetzt die richtige Position und können auf dem TV mit der entspr. Nummer angewählt werden. Vielen Dank noch einmal für deine Hilfe. Eine Spende ist bereits überwiesen!
Alle Gute!
Uwe
