### ISSUE TITLE
Can't open HUMAX exported channels (.qdf)

### ISSUE THREAD

**Issue by yalramadan** [PredatH0r/ChanSort#247]
Hi, 
My Humax HD-Mini exports the channels as (.qdf) but that's apparently not supported by ChanSort :(

Is there a way to make it compatible with the amazing ChanSort? Or can that be supported in a future release?

I attached the exported channels file 
[Humax Export.zip](https://github.com/PredatH0r/ChanSort/files/6850886/Humax.Export.zip)

Best regards,
Yahya

**Comment by PredatH0r** [comment]
Unfortunately your receiver useses some unknown compression/encryption method and makes it impossible to see any channel data.
![grafik](https://user-images.githubusercontent.com/6238104/127107227-ddf9d928-88e7-43d9-b359-1594271e59d3.png)
