### ISSUE TITLE
HiSense H55M330 not readable.

### ISSUE THREAD

**Issue by Subtixx** [PredatH0r/ChanSort#249]
[channel.zip](https://github.com/PredatH0r/ChanSort/files/6885152/channel.zip)
> No plugin found to read/write G:\channel.db files.
> ChanSort.Loader.Hisense.dll (Hisense (channel.db, servicelist.db)): File doesn't contain svl_* tables

**Comment by PredatH0r** [comment]
Can you please attach your file to the github report so I can take a look?
(replies with e-mail attachments will get lost, only direct uploads on the github web page work)

**Comment by Subtixx** [comment]
I've seen the channel.db is empty when I export it. However when I add channels to the favorites it does export them, but the app is still saying no plugin found

**Comment by PredatH0r** [comment]
In deine Senderlistendatei enthält leider keine Sender- und Transponderdaten (Tabellen svl\_\* und tsl\_\*fehlen), sondern nur die Favoritenliste 1 (Tabelle fav\_1), in der dann aber Verweise auf die nicht vorhandenen Senderdatensätze enthalten sind (ui2\_svc\_rec\_id).

Ich vermute, dass beim Sendersuchlauf eine vordefinierte Senderliste ausgewählt wurde (z.B. durch Auswahl deines Kabelanbieters oder eine Liste ala "Astra 19.2 Deutschland". Derart vorderinierte Listen können nicht exportiert und extern bearbeitet werden, diese sind fest in der Firmware eingebaut.

Hier hilft nur ein neuer Sendersuchlauf, bei dem du unbedingt neutrale Optionen wie "keiner", "anderer" bzw. "Blindsuche" auswählen musst. Danach exportiert der Fernseher eine vollständige Datei inklusive der Sender- und Transponderinformationen.

Hier zum Vergleich oben deine Datei (channel) und darunter meine Senderliste (channel0) mit SQLiteStudio geöffnet.
svl\_3 ist die Tabelle für DVB-S, svl\_2 wäre DVB-T und svl\_1 DVB-C

![grafik](https://user-images.githubusercontent.com/6238104/127161224-df09fc0b-3dd3-4e42-9c22-203f317a0ddd.png)

**Comment by Subtixx** [comment]
Thanks. Using "other" in everything worked.
