### ISSUE TITLE
Editing M3U adds channel number to channel name

### ISSUE THREAD

**Issue by Double-A-92** [PredatH0r/ChanSort#253]
I used ChanSort to filter and order a M3U IPTV playlist.
It worked good but it added the Channel or Order number to the Name, which is a bit annoying.

E.g. out of ...

#EXTINF:0001 tvg-id="Rai1.it" tvg-chno="116" group-title="Entertainment" tvg-logo="https://blub/rai_1_hd.png", **Rai 1 HD**
https://blub/channelId=rai_1_hd

... it made ...

#EXTINF:0001 tvg-id="Rai1.it" tvg-chno="116" group-title="Entertainment" tvg-logo="https://blub/rai_1_hd.png", **1.  Rai 1 HD**
https://blub/channelId=rai_1_hd

Is there an option to disable that? And if yes, I think it should not be enabled by default :)

**Comment by PredatH0r** [comment]
Unfortunately there is no option for that in the current build.
I'll upload a new build in a couple minutes that will auto-detect whether the original file had prefixed numbers and only in this case it will write them to the output file.

For your case to get rid of the already existing numbers, you can open an original file (e.g. a copy of the .bak file that ChanSort created) and apply your current file (that has the numbers added to them) as a reference list.

**Comment by PredatH0r** [comment]
I just realized that this is already implemented that way.
ChanSort only writes the prefixed numbers if every single channel in the file already had a prefixed number.

To get rid of the numbers, you can
open the .m3u file in a text editor and remove the number from one channel, 
open the file with ChanSort
make a change like swap #1 and #2 and then back again (without any changes, "Save" does nothing)
save the file
verify with a text editor that the numbers are gone

**Comment by Double-A-92** [comment]
Oh yeah, I was using an older version of the software. Sorry about that. The actual version now works as expected :)
