### ISSUE TITLE
LG OLED65C17LB

### ISSUE THREAD

**Issue by sinumeriker** [PredatH0r/ChanSort#254]
Hello,

I would like to sort the channel list of my new LG OLED65C17LB (2021) with ChanSort.
I followed the instructions for the program search to be able to import the channel list.
But I'm not able to import the list. An error message appears during import.
Details:
software version: 3.15.36 (releas 07/27/2021)
webOS TV-Version: 6.1.0-2701

For a test I have moved "RTL Television" from pos. 919 to pos. 1 and saved the file.
The import was not succesfull.
Attached the original and the manipulated file:
[GlobalClone.zip](https://github.com/PredatH0r/ChanSort/files/7023506/GlobalClone.zip)

All your help is apreciated.

Best regards

sinumeriker

**Comment by PredatH0r** [comment]
I can only guess that your USB stick is formatted with NTFS.
LG and many other TVs have trouble reading and writing from sticks with the NTFS file system.
I recommend to use a stick <= 32GB and format it as FAT32 (Windows does not allow to format a stick >32GB as FAT32).
Windows sometimes uses exFAT for large sticks, which is not understood at all by TVs / Linux.

Another possible cause is the file name.
While older LG TVs allowed to select a file with different numbers than 00001, I think webOS requires that the list has the name GlobalClone00001.TLL (no other number, nothing appended to the file name).

**Comment by sinumeriker** [comment]
Now it works fine!!
Just the filename was the problem.
It only works a file named GlobalClone00001.TLL, nothing else will work to import.
Thank you for your great support and this amazing tool.

Best regards

sinumeriker
