### ISSUE TITLE
Philips 32PFL3118K/12 Support

### ISSUE THREAD

**Issue by umitseyhan75** [PredatH0r/ChanSort#258]
Hi, this tv gives me a ".BIN" file in a "repair" folder which I can not edit wtih ChanSort. What can we do about this?
Sample file:
[Repair.zip](https://github.com/PredatH0r/ChanSort/files/7076391/Repair.zip)

**Comment by PredatH0r** [comment]
Hi!
Your TV writes 3 files to the USB stick, all of them are contained in the ZIP file you uploaded.
While the .bin file is visible, the TV marks the other files as "hidden" and you can only see them in a Windows Explorer when you enable the option to view hidden files (Menu "View / Hidden Elements").

The actual channel list is the file named CM_TPM1012E_LA_CK.xml. This file can be edited with ChanSort.
If you try to open the .bin file, ChanSort will instead automatically try to open the .xml file in the same folder.
This works fine if you try to open the .bin file directly on the USB stick, but if you copied the .bin file to your hard drive (without the hidden files), then ChanSort can't find the .xml file and is unable to edit anything.

**Comment by umitseyhan75** [comment]
Well, that is not working.
![pR7w64kfj0](https://user-images.githubusercontent.com/43583375/131385958-82e36278-bd13-47e3-aced-55d808ac4d29.gif)

**Comment by PredatH0r** [comment]
There must be something wrong with your ChanSort installation.
The message box doesn't mention a single "ChanSort.Loader.*.dll" module that tried to load the .bin file - and there should be several.
I can only guess that either an anti-virus tool is blocking ChanSort from loading the DLLs (because they were downloaded from the internet) or you didn't extract all the files from the ChanSort .zip into the same directory.

I unzipped your file to a USB drive and could open the list with ChanSort 2021-07-27 (the same version you used) without any problems.

**Comment by umitseyhan75** [comment]
I just unzipped the folder (whic is named as "ChanSort_2021-07-27") to dektop and run"ChanSort.exe" (also tried to run as administrator). Is there something I am doing wrong with the "installation"?
I am using Comodo antivirus to disable Windwos defender and I am pretty sure I disabled every single component of it and whitelisted. So if there is nothing I am missing AV do not mess with me.
What do you suggest me for troubleshoot this?

**Comment by PredatH0r** [comment]
I used one of my other PCs to test this, it also worked fine there.
I downloaded ChanSort 2021-07-27, with Firefox, right-clicked on the .zip and used 7zip's context menu "Extract here".
I did the exact same with your Repair.zip, so now I have a "ChanSort" and a "Repair" folder inside my Downloads folder.
I started ChanSort.exe and then selected the .bin file in the Repair folder, which loaded the list.

By using Firefox and 7zip I probably don't run into issues that other uses have when they use Chrome or Edge and the standard Windows Explorer or WinZip to extract .zip files:

Some browsers add information to downloaded .zip files that indicate they were downloaded from the internet.
If you extract the .zip with the normal Windows Explorer or with WinZip, it will then also mark all the .exe and .dll files with the information that they were downloaded from the internet. When you right click the ChanSort.exe, go to Properties, it might show on the bottom of the General page that the file is from another computer and may be blocked.

I tried again with Chrome, opened the .zip with the Windows Explorer and then copy+pasted the ChanSort folder to some other folder outside the .zip, right-clicked ChanSort.exe and then I saw the information with a checkbox to unblock the file.
However, on my machine even that ChanSort.exe opened your list without isses even without unblocking it explicitly.
Maybe checking "Allow" in the Properties works for you. I don't know if the same thing needs to be done for the ChanSort.Loader.Philips.dll file then.

![image](https://user-images.githubusercontent.com/6238104/131413212-de62940d-e072-4691-9d8d-cab719feedc7.png)

**Comment by umitseyhan75** [comment]
I downloaded it IDM but tired to Firefox now. Already using 7zip btw.
Result is same, yet I do not have that indication.
![resim](https://user-images.githubusercontent.com/43583375/131416950-23fd05e1-b4f7-403b-8a8b-b9c87009eb94.png)

Any other suggestion? We can setup a remote connection If you want to check yourself.

**Comment by PredatH0r** [comment]
A remote connection / TeamViewer would be interesting. I'm available pretty much all day today (from now till about 20:00 CEST).
I tried it with 2 more Windows installations today (a Win 10 Pro VM and a Win 11 Pro VM), on both using Edge and the Windows Explorer - no issues there.

**Comment by umitseyhan75** [comment]
Alright, have discord?

**Comment by PredatH0r** [comment]
PredatH0r#7233

**Comment by PredatH0r** [comment]
- fixed issue with upper/lowercase handling of file extensions (.BIN vs .bin) with Turkish language Windows locale
- disabled deleting of channels for this file format (it causes desync between channels in the TV's menu and tuner)
