### ISSUE TITLE
Philips 32PFS5603 Öffentliche Sender Verschlüsselt nach sortierung

### ISSUE THREAD

**Issue by Zoltan82** [PredatH0r/ChanSort#259]
Hi,
Leider kann ich nur auf deutsch, ich hoffe es kein Problem.
Nach Sender Sortierung sind die öffentliche Sendern verschlüsselt. Kann diese Probleme behoben? (Z.b.: Das Erste,ZDF, etc) Sind normalerweise unverschlüsselt.
danke

**Comment by PredatH0r** [comment]
Hallo Zoltan,

in letzter Zeit häufen sich leider die Problemberichte bezüglich Philips-Listen. Ich bin gerade dabei, eine neue Version zusammen zu stellen um hoffentlich einige der Probleme zu beheben.

Kannst du mir bitte deine Senderliste schicken oder hier hochladen (ein .zip des Repair oder ChannelMap_xxx Ordners)?
Hast du auch Sender gelöscht oder nur verschoben? Löschen werde ich künftig sperren, da dies bei Philips-Listen immer zu Problemen führt.
Mir sind mittlerweile 10 verschiedene Philips-Dateiformate untergekommen, da ist es wichtig, so viel wie möglich über die konkrete Situation zu wissen.

**Comment by Zoltan82** [comment]
Danke für dein Antwort,
In Anhang findest du 2 Datei, original und edited und ein screenshot von ein Fehler bei öffnen. 
Nur zur Info bei paar sender die buchstabe ö und Ö sind auch nicht richtig.
Ich hab nur sender verschoben nicht gelöscht.
Gruß
[ChannelMap_100_edited.zip](https://github.com/PredatH0r/ChanSort/files/7104355/ChannelMap_100_edited.zip)
[ChannelMap_100_original.zip](https://github.com/PredatH0r/ChanSort/files/7104356/ChannelMap_100_original.zip)
![buchstaben fehler](https://user-images.githubusercontent.com/89992591/131974338-2de1af9c-ab92-40d7-9b29-acc2c797d612.jpg)
![edited liste](https://user-images.githubusercontent.com/89992591/131974342-b5a890b0-3ff2-4a6c-8bab-48957588be24.jpg)
![original liste](https://user-images.githubusercontent.com/89992591/131974345-2fbb550c-d4fe-4aa6-b9fc-7b729522fbca.jpg)

**Comment by PredatH0r** [comment]
Danke für die Infos, ich sehe mir das Ganze gerade durch.
Was mir sofort auffällt: Es gibt anscheinend 2 Varianten von Geräten, die einen "ChannelMap_100"-Ordner exportieren. 
Bei der mir bisher bekannten Variante, die mit ChanSort funktionieren sollte, werden im channellib und s2channellib Ordner nur .xml Dateien erzeugt. Dann gibt es aber auch noch eine Variante wie bei dir, wo zusätzlich auch dtv\_cmdb\_*.bin Dateien exportiert werden, in denen ebenfalls eine komplette Senderliste enthalten ist.
Ich weiß leider nicht, ob der Fernseher dann auch immer .bin + .xml beim Import erwartet und womöglich durcheinander kommt, wenn ChanSort nur die .xml ändert, oder ob man eventuell die .bin atv\_ und dtv_\ .bin Dateien löschen kann und sich der Fernseher dann beim Import wie die andere Variante verhält.

Ich werde jetzt jedenfalls noch kontrollieren, welche Änderungen ChanSort da wirklich durchgeführt hat und ob es da eventuell Auffälligkeiten gibt, z.B. das bezüglich Umlauten.

**Comment by PredatH0r** [comment]
Ich habe jetzt eine neue Testversion von ChanSort hochgeladen: https://chansort.com/ChanSort_2021-09-03.zip
Mit dieser Version habe ich deine Originalliste geöffnet und dann deine Edited-Liste als Referenzliste darauf angewandt.
Ergebnis ist diese neue Liste: [ChannelMap_100_edited-new.zip](https://github.com/PredatH0r/ChanSort/files/7107370/ChannelMap_100_edited-new.zip)
Diese hat jetzt die gleiche Datensatzreihenfolge wie das Original bzw. die .bin Datei und ändert nur noch die Programmnummern. Somit sollten jetzt Sendernamen, Programmnummer, Verschlüsselung im Menü (.xml) wieder mit den Daten des Tuners (.bin) zusammenpassen.
Ich habe auch die Dateien vor und nach der Änderung verglichen (neue .xml und .xml.bak), außer den Programmnummern gibt es keine Unterschieden - auch nicht bei den Sendernamen und den Umlauten. Das dürfte also ein Fehler in der Fernseherfirmware sein, dass die zu Sonderzeichen werden. Vermutlich passiert das auch, wenn du die Originaldatei unverändert wieder in den TV importierst.

**Comment by Zoltan82** [comment]
Danke deine Mühe!!
Ich kann erst morgen in der Werkstatt ausprobieren. Wenns geht nicht soll ich mit Fernbedienung sortieren. Fernseher hab ich auf neueste Version updated und mehrmals zurückgesetzt leider ohne Erfolg. 
Sonst bin sehr dankbar für Chansort weil ich nutze täglich bei Fernseher Lieferungen.
Ich melde mich morgen.
Danke

**Comment by PredatH0r** [comment]
Noch eine Frage: nutzt du eine spezielle Methode für den USB-Export am TV?
Mir ist aufgefallen, dass jene Listen mit einem "Clone\\Repair" Ordner diese atv/dtv\_\*.bin Dateien enthalten, und die ohne "Clone" nur .xml Dateien in channellib bzw. s2channellib.
Gibt es da womöglich einen Geheimcode oder eine extra Service-Fernbedienung für die "Clone" Funktion oder ist das der ganz normale USB-Export aus dem Menü bei dir?

**Comment by Zoltan82** [comment]
Hi.
Rückmeldung: Mit dein Chansort Version und edited liste funktioniert 1A. Kurz hab ich umsortiert nach Kunde liste, klappt es auch.
Die Übertragung hab ich ganz normal mit original Fernbedienung gemacht. Danke deine Hilfe, hast viel zeit für mich gespart!!

**Comment by PredatH0r** [comment]
Super, zur Abwechslung einmal eine Erfolgsmeldung bezüglich Philips :)
Noch eine letzte Frage: sind die Umlaute immer noch durch Sonderzeichen ersetzt oder funktionieren die jetzt auch?
(geändert habe ich diesbezüglich ja nichts)

**Comment by Zoltan82** [comment]
ö und Ö sind normal. 
Aber dann weiß ich echt nicht warum geht es plötzlich tadellos...

**Comment by PredatH0r** [comment]
Ich kann da leider auch nur raten. 
In der alten Version standen die Senderzeilen alle in geänderter Reihenfolge in der Datei und der Fernseher hat dann alle Sender umbenannt und neue Nummern zugewiesen - aber immer noch die alten Sender angezeigt.
Mit der neuen Version/Liste versucht der Fernseher eventuell nicht mehr, die Sender umzubenennen (weil sich nichts geändert hat) und damit bleiben dann auch die korrekten Namen erhalten.
Wie es wirklich abläuft können wohl nur die Philips Firmware-Entwickler beantworten. Gut jedenfalls, dass es funktioniert :)

**Comment by PredatH0r** [comment]
Ein letztes Attentat hätte ich noch: Könntest du bitte diese Datei ausprobieren? 
[ChannelMap_100_edited-favLockHideRename.zip](https://github.com/PredatH0r/ChanSort/files/7109630/ChannelMap_100_edited-favLockHideRename.zip)

Darin sollten jetzt Favoriten gesetzt sein: 1=ZDF HD, 2=Das Erste HD
Sender 3 "BR Fernsehen Süd HD" sollte die Kindersicherung aktiv sein. Der Fernseher sollte nach einem Passwort fragen.
Sender 4 "WDR HD Köln" habe ich zum Testen der Umlaute umbenannt auf "WDS HD Köln ÄÖÜäöüß".
Sender 8-15 "Sky ..." bis "Beate Uhse" habe ich auf "versteckt" gesetzt.

Wäre toll zu wissen, ob das vom Fernseher auch genau so umgesetzt wird.
Damit könnte ich dann endlich sagen, dass diese Dateiformat vollständig funktioniert.

Die verwendete Programmversion liegt auf https://chansort.com/ChanSort_2021-09-04.zip

**Comment by Zoltan82** [comment]
Hi. Gerne aber leider hat Kunde schon diese Philips mitgenommen, praktisch ich hab in Werkstatt kein Gerät mehr.. Es tut mir leid.
