### ISSUE TITLE
Request: Improve SAT>IP M3U support

### ISSUE THREAD

**Issue by lars18th** [PredatH0r/ChanSort#268]
Hi,

My use-case of the M3U filelist is a local SAT>IP server that provides access to DVB-C/T/S tuners with FTA signals. I use this file with VLC, IPTV player and other Android Apps, plus some WMC and TVHeadend instances. So then my M3U file has a lot of data, and the current implementation of the ChanSort fails to load this file or has other troubles.

So based on my experience, I want to contribute with some suggestions:

- **Enhanced #EXTM3U**: When reading a M3U file the current implementation fails if the first line is not `#EXTM3U`. However, it's common for some clients to found in this line some tag, like `url-tvg=` to indicate a source for the EPG. Then the first change that you can implement is to support `#EXTM3U` _at the start of the line_, maintaning the rest of data until the end of the first line.
- **VPID and APID**: The values of these two columns could be erroneous as from a SAT>IP request you don't have the information of which pid is the audio/video. At time you get the fixed positions 4 and 5, assuming that these are the vpid and apid. But, why this? I suggest to give the user the option to select the vpid/apid positions or leave them blank. This will be more user friendly.
- **SatPosition**: I recommend to enable this value to map the "src=" parameter of the SAT>IP specification that indicates the orbital position. This could be the generic DiseqC values AA,AB,BA,BB or 1..8/16/32/64 ranges, as you prefer (more easy the integer number).
- **Satellite**: Now this value indicates the transport method to access to the stream (i.e. "rtps://server:port" or "http://server:port"). And that's great. However, I suggest a method specific for SAT>IP to "edit" this value. For example, change between "http://<-->rtps://"; replace the address i.e. "192.168.1.40<-->satip.local"; and the port i.e. ":8080<-->:554". Then it will be more easy to "edit" some list changing from one server to another.
- **Terrestrial/Cable support**: The current implementation targets only Satellite sources.  My suggestion is to check the "msys=" parameter to know if the source is Sat, Ter or Cab.

I hope you want to consider some of these suggestions. Perhaps all or perhaps only some. In any case I'll be confortable if you almost are listening.
Regards.

**Comment by lars18th** [comment]
Hi,

After many weeks passed... no comments about my last request? Any news about the M3U support for SAT>IP servers?

**Comment by PredatH0r** [comment]
My apologies.
Since November I am working on my business projects 7 days a week, 10 and more hours a day and didn't find any time to work on ChanSort since. But I am positive that there will be time again soon and I will consider your suggestions.

**Comment by lars18th** [comment]
Hi @PredatH0r ,

Don't worry. It's a simple "ping reminder". Please take your time, and when you may, post what you can.

Regards.

**Comment by lars18th** [comment]
Hi @PredatH0r ,

I close this issue because it's quite old. I hope you want to consider my last requests in #335 .
