### ISSUE TITLE
After write file Menu Installation in LG 49UF695V not show

### ISSUE THREAD

**Issue by pepeEL** [PredatH0r/ChanSort#28]
Hi
I found bug. After edit GlobalClone0001.TTL file and then write to my TV i try open MENU INSTALLATION(where i can download or upload file TTL). This menu after write moded file not open. After reset TV to factory menu open ok. After write file again not open.

When i download TTL files and again write not moded file xxUF695V-ZA00001.TLL menu installation works ok. But in your soft CahnnSort i can not open file xxUF695V-ZA00001.TLL to edit.
With write GlobalClone0001.TTL is problem after write to TV. Menu installation never open.

**Comment by PredatH0r** [comment]
All that chansort changes are the channel numbers and the flag whether the number was manually changed. So I can only assume that the TV's firmware is bugged and disables the menu whenever you import any file.
You could test it by editing the original file manually with notepad++ and change one of the channel numbers. Or even try to re-import the unmodified file. If the menu is disabled afterwards, then it's clearly the firmware that's broken.
Unfortunately I don't have a WebOS based LG TV to test this out myself.

**Comment by pepeEL** [comment]
When i write unmodified file menu works ok.

But in notepad++ i can edit filexxUF695V-ZA00001.TTL ?

**Comment by PredatH0r** [comment]
Only the GlobalClone is a text file and can be edited.
The ZA00001 is a binary file format specific to the particular model and firware version in your TV. I don't know any program that can edit this file (for your model/firmware).
Did you delete this file from the stick when you did the import? If not, then your TV will read that file and ignore the GlobalClone.

**Comment by pepeEL** [comment]
Yes i delete file ZA0001... on stick i have only GlobalClone0001.TTL and when i write to TV i select GlobalClone0001.

When i write unmodified file GlobalClone001.TTL all is ok and i can open again MENU INSTALLATION. When i write modified file i can not again open MENU INSTALLATION and must reset to factory my TV.

But what is write in binary file ZA001.TTL ?

**Comment by pepeEL** [comment]
please help :(

**Comment by PredatH0r** [comment]
I'm afraid that there is nothing I can do.
When the LG firmware disables the menu for no aparent reason, then only LG can fix that error in the firmware.
I don't have an LG TV with WebOS, so I can't run any test on such a TV to try finding any possible workarounds.

I see you tested loading a modified GlobalClone, and the menu became disabled aftwards. And you loaded an unmodified ZA00001 file, and the menu worked afterwards.
The important test would be to load an unmodified GlobalClone. If that also disables the menu, then we have proof that there is something wrong with the firmware.
