### ISSUE TITLE
Massive problems with LG OLEDC1, WebOS6, Unicable II

### ISSUE THREAD

**Issue by Bodenseematze** [PredatH0r/ChanSort#286]
I have a new LG OLED48C17LB with WebOS 6.2 which I want to use as SAT-Receiver with Unicable II (Jessy) configuration - only Astra 19.2
I go to the SAT settings, configure everything (Unicable II, dual, ...)
Then I did a scan for the programs (Dual, SAT, "other providers", blind and network scan) - it takes about 15 min. and it finds about 1050 TV and 180 radio programs.
Which are totally randomized in the list - so I did an export of the list to an USB stick and edited them with ChanSort - starting a complete new list and adding all the unneeded programs at the end (no template).
The first time I then re-imported the sorted list the TV got the correct program numbers - but when I tried to switch to one of the programs it shows "no signal".
Then I went again to the SAT settings (by loosing my list again) and found, that the "Unicable II" setting has been changed to "Unicable I" and also wrong channels/wrong frequencies.
I corrected them to the original valuand again did a new scan.
After that I tried to reimport the sorted list again - now it doesn't respect the numbering and just did some more random sort and it also shows "no signal" again - when I reenter the SAT settings I can see it again changed it's values; now Unicable is completely switched off...

What's going on here?
I need a sorted list - not some random sorted programs...

[GlobalClone00001.zip](https://github.com/PredatH0r/ChanSort/files/8054206/GlobalClone00001.zip)

And BTW, how does LG think their user sort the big list of programs? With their "sendermanager"? That's a joke, isn't it?

**Comment by PredatH0r** [comment]
I created ChanSort around 2010 when I bought my first LG TV (42LM620S) where it was as good as impossible to sort 1512 Astra 19.2 channels (jumping 30 pages forward, selecting a channel, jumping 30 pages backward, drop the channel. repeat 50 times).

Since then a lot of different channel list formats were created by LG, and with WebOS5 and 6 were actually a big step backwards. They totally forgot to add data for the favorite lists to the file, which was part of all previous versions.
LG has never offered any tools for editing the List on their own, so I can only guess that they do barely any testing if their firmware can actually export and import data correctly. I have seen cases when direct export+import (without modifications) caused randomized lists.

My guess is that LG added the export+import options for situations where the list of one TV should be cloned to other TVs (e.g. in a hotel, hospital, ...). In such scenarios the receiving device usually has no channel list loaded at all and the import is done into an empty device. So maybe it works for you to reset your TV to defaults or start a search and cancel it immediately to clear the channel list before you import the list. (The scan can be skipped after a factory reset).

I do know of successful imports even without a reset, but those were standard Sat/Cable connections and not Unicable. I have no idea what kind of bugs are in the LG firmware in such scenarios.

Can you also please upload your GlobalClone00001.tll.bak file? This is a backup copy of the original file, automatically created by ChanSort, so that I can compare it to your modified file and make sure that really only program numbers where changed by ChanSort.

**Comment by guba-sat** [comment]
First of all, I can read and understand English, but I can't write it. Therefore the whole thing is translated with Deepl .
********************
In the file of Bodenseematze are the Unicable settings:
ID 10 frequency 1164
ID 15 frequency 1458
LG counts internally as well as the LNB from zero, therefore in the file "UBSlot":9 or "SubUBSlot":14
The IDs can also be used directly next to each other, e.g. 9/10, 15/16.
LNB I guess Inverto Unicable/JESS.

Once make a factory reset, set language, etc. do not make transmitter settings , but quit. Then directly import the file

Attached a tutorial that I had written in January, with the same model
[Unicable_LG_WebOS_5_6_1-2022.pdf](https://github.com/PredatH0r/ChanSort/files/8063131/Unicable_LG_WebOS_5_6_1-2022.pdf)

@PredatH0r
I had sent you a mail on Nov 27, did you see it?

**Comment by PredatH0r** [comment]
Ich bin seit Anfang November leider 7 Tage die Woche 10-12h an meinen beruflichen Projekten am Arbeiten und konnte mich nicht um ChanSort kümmern. Gerade einmal zwischen Weihnachten und Neujahr gingen sich ein paar freie Stunden aus.
Dein Mail habe ich gerade gefunden und werde es mir noch im Detail ansehen.
Ab März sollte dann wieder etwas Zeit für ChanSort übrig bleiben.
Sorry dass da derzeit bei mir nichts weiter geht.

**Comment by Bodenseematze** [comment]
Das ist ein Freizeitprojekt - und wenn Du aktuell keine freie Zeit für das Projekt hast, dann ist es so...
...da musst Du Dich nicht für entschuldigen! 😉

Ich habe inzwischen die Liste so nach und nach im Fernseher (!) von Hand sortiert.
Eine absolute Sisyphusarbeit - aber inzwischen ist es geschafft...
...ich frage mich nur, ob die Liste nicht irgendwo auf dem Fernseher in dessen Dateisystem liegt und man sie ihm nicht hätte direkt "unterschieben" können (also ohne Ex-/Import) - per sftp oder so.
Auf jeden Fall kann ich überhaupt nicht verstehen, dass lt. vielen Tests dieser Fernseher zu den aktuell besten gehören soll. Die Bedienung ist in meinen Augen sowas von miserabel und fie Umschaltzeiten sind auch recht lang - ich kapiere nicht, dass das in keinem Test, den ich gelesen habe, erwähnt wird...

**Comment by guba-sat** [comment]
@Bodenseematze: Das Aufnehmen hatte ich bis jetzt nicht ausprobiert.
Die Einstellungen bleiben drin: Bei Dir: _SubUBFrequency":1458_,"LNBPower":true,"MotorPos":0,_"UBSlot":9,"_MDUType":0,"NetworkSearch":true,"ConnectionL1":0,"ConnectionL2":0,"LNBTypeUniNor":true,"MotorizedSystem":0,"satelliteId":"0192",_"UBFrequency":1164_,"ScanSearchType":"ALL",_"SubUBSlot":14,_ (zählt ab 0)
Auch wenn man nachträglich im TV nachschaut, sind sie noch drin. Bei mir war es vorgestern auch noch so. Nur steht es wie bei Neuprogrammierung auf Unicable-1, die IDs selber waren, wenn man auf Unicable-2 umstellt, immer noch drin. Bei Uni-1 werden auch nur 4 IDs angezeigt. Allerdings ist dann, wenn man abbricht und exportiert, die entsprechende Channellist des "geänderten" Sat leer. Ich darf bei meinen drei Satelliten, z.B. beim Einlesen von 28.2 nicht sagen "neu stimmen" sondern muss "Programme beibehalten". Sonst sind Astra 19 und Hotbird weg und nur 28.2 in der Channellist.
Tests: Da wird ja auch nur Bildqualität, Tonqualität, Ausstattung und Energieeffizienz getestet ... (z.B. Chip)

**Comment by Bodenseematze** [comment]
@guba-sat: ohne Aufnahmetest ist ja nicht sicher, ob auch wirklich beide Tuner funktionieren (PiP gibt es bei diesem Modell ja leider auch nicht mehr)... ;-)

In welchen Dateien (auf dem Fernseher) finde ich die Einstellungen und wo die Kanalliste?
Könnte ich die per ssh-/telnet-Zugriff direkt auf dem Fernseher ändern (mit Texteditor) - root und Homebrew-Channel habe ich drauf...?

Es bringt mir ja nichts, wenn die Einstellungen noch drin sind und sich "nur" von Unicable II auf Unicable I zurückstellt - ich habe ja keine Möglichkeit, das ohne Verlust der Kanalliste wieder zu korrigieren :-(

Tests: naja, ich hab da im Vorfeld auch Tests gelesen, die über die Bedienung geredet haben - aber dass das so mies ist, stand nirgends.
Auch dass die Umschaltzeiten von einem Programm zum anderen so lang sind (stört mich ungemein) stand nirgends.

Vielleicht bin ich durch meinen bisherigen Receiver verwöhnt (Gigablue Quad Receiver mit älterem HDFreaks Linux-Image) - der war in allen Belangen deutlich besser - nur leider hat er zum Hoch- und Runterfahren lange gebraucht und der "Women's Acceptance Factor" war eben nicht gegeben (z.B. "wieso brauche ich zum Fernseher dazu noch so viele andere Fernbedienungen - das ist mir alles zu kompliziert" oder "wieso muss ich da zwei Minuten warten, nachdem ich [per Schaltersteckdose] eingeschaltet habe?")

**Comment by guba-sat** [comment]
@Bodenseematze:
Einstellungen und Kanalliste sind alle im GlobalClone enthalten. Einzig fehlen leider bei den TVs mit WebOS die Favoriten. Diese sind im TV selbst.
Ich habe mal deine Originaldatei kommentiert. den grössten Teil der Kanalrecords habe ich rausgeschmissen.
Alleine «deleted»-Records hat es schon 1350 Stück. 
Was mich stört, sind die «falschen» Frequenzen, die der Blindscan findet und nachher die richtigen Frequenzen «deleted», da ja die Programme schon eingelesen sind.
Ich würde deine jetzige sortierte Senderliste im TV exportieren und als Backup aufbewahren. Dann kannst du jederzeit diese wieder einlesen. Ich mache es immer so, bevor ich ein neues File einlese, exportiere ich das funktionierende vom TV und kann dann jederzeit wieder zurück.
Uni 1 oder 2 merkt scheinbar der TV selbst anhand der ID-Nr. Nur für Unicable ein hat es ein Flag: "LNBTypeUniNor“:true
Eigentlich musst du ja nicht mehr in die Sateinstellungen, wenn es funktioniert. Einfach «weiter» zum Suchlauf und dann «bestehende Programme behalten», dann sollte er nur noch «nicht vorhandene» Programme einlesen
[GlobalClone_original_kommentiert.pdf](https://github.com/PredatH0r/ChanSort/files/8134571/GlobalClone_original_kommentiert.pdf)

Den Aufnahmetest mache ich noch. Der TV steht beim ehem. Senior-Chef. Ich mache die Tests meistens, wenn er nicht anwesend ist (ist seine Zweitwohnung).

**Comment by guba-sat** [comment]
@Bodenseematze:
Hatte vorhin den Aufnahmetest gemacht und es funktionierte durchgeschleift und Antenne an SUB.
Programmierte die Aufnahme über den Programmführer. Auf dem «Sehprogramm» habe ich sogar rumgezappt. Die HD steckte am USB2. Bei Beginn musst du den HD-Anschluss auswählen (heisst nicht USB). Anhand der Speichergrösse der HD auswählen.
Was natürlich nicht gleichzeitig geht, Live-Playback und Aufnahme auf die gleiche HD.
[Live-Playback_Aufnahmen.pdf](https://github.com/PredatH0r/ChanSort/files/8270335/Live-Playback_Aufnahmen.pdf)

**Comment by guba-sat** [comment]
![LG_copies_programmes](https://user-images.githubusercontent.com/99670077/197057573-21e4c4d7-4b97-431e-93a9-27d15d722254.png)

**Comment by PredatH0r** [comment]
> @PredatH0r Do you remember how you accesed the menu that permits channels to be exported for 42LM620S ? Nothing seems to work :( thanks!

The original LM620S firmware required a special "service remote control" to access the hotel menu. I was using a Logitech Harmony for that purpose that could emulate the required signal.

The current firmware works with the normal remote control, using the same key combination as the older LV/LW models.
Details can be found on the bottom of https://github.com/PredatH0r/ChanSort/wiki/LG
