### ISSUE TITLE
Run on linux!

### ISSUE THREAD

**Issue by skydiablo** [PredatH0r/ChanSort#289]
Hi!
i know, this is not your destination OS but have you any suggestions how to run this tool on linux? i have tried with wine/bottle but no success. maybe someone can give me an setup how to run it on linux?

regards, volker.

**Comment by PredatH0r** [comment]
Hello Volker!

Instructions on how to run it on Linux can be found near the bottom of https://github.com/PredatH0r/ChanSort

A user also provided information on how to run ChanSort with Docker: https://github.com/PredatH0r/ChanSort/issues/285

Cheers,
Horst

**Comment by skydiablo** [comment]
oh ;) big thx! RTFM :D:D:D:D
