### ISSUE TITLE
I ran into a bug that doesnt let me progress with ChanSort

### ISSUE THREAD

**Issue by PeterQuillz** [PredatH0r/ChanSort#293]
When i try to "apply order from a reference list"  it opens this window 
https://i.imgur.com/ez44N7x.jpg
and i cant reach the bottom of the window to confirm it. Options to maximize the window or change its size are disabled, there's no way to scroll down like a scrollbar or anything. I tried windows commands, different monitors, different screen resolutions, external resizer programs. no luck. I cant progress with the program when i cant reach the bottom of this window.
I'm using windows 10 , 24" monitor, screen resolution is 1920*1200 and program version I'm using is ChanSort_2022-03-20

Note: I'm not talking about the  ChanSort main window but the one that opens when i  "apply order from a reference list" .  It makes progressing with the program impossible when i cant reach the bottom of that window.

**Comment by PeterQuillz** [comment]
Bug still exist  in ChanSort V  2022-04-12

**Comment by PredatH0r** [comment]
I was unable to reproduce the problem.
The dialog has a size of about 720x730 pixels in the designer (based on 92 DPI and the size of Tahoma 8,25pt) and gets scaled according to Windows' scale factor (100%, 125%, 150%, 200%, ...).
Anyhow, I changed the dialog to have a resizable border starting with version 2022-04-18 (yet to be released) and it will contain scroll bars when the size goes below the 720x730 that it was designed for. I hope this helps.

**Comment by PredatH0r** [comment]
Implemented in version 2022-04-19
