### ISSUE TITLE
Add Support for Orsay OS TVs (T-M14HKDEUCB)

### ISSUE THREAD

**Issue by Gabrimax98** [PredatH0r/ChanSort#294]
I've encountered an older TV whose .zip file isn't supported.
[T-M14HKDEUCB.zip](https://github.com/PredatH0r/ChanSort/files/8389584/T-M14HKDEUCB.zip)

I've noticed these older TVs are not structured as Tizen OS TVs (KTMDEUCB and newer), they don't have a tv-chms.zip inside of their TV Clones.

Would be awesome if you could add support for these too!

The TV is a HG32EE690DB, in case it's needed.

**Comment by PredatH0r** [comment]
This type of TV seems to use the older .scm channel list format.
Your T-M14HKDEUCB.zip file contains a "Clone" folder. If you have 7-zip, you can select all the files in that folder, right click, "7-zip > add to Clone.zip" and then rename the archive to channel_list_HG32EE690DB_1201.scm. (this name pattern is important to detect the correct format and version. it's also important that the .scm/.zip contains all the files in the root folder and not in a subfolder).
The resulting .scm file can be edited with ChanSort.

When done editing, you have to reverse the process. Unzip the .scm file again to replace the files in the Clone folder, then zip the whole T-M14HKDEUCB.zip again.
When I find some time I'll add support to directly open/edit the T-M14HKDEUCB.zip without the manual back and forth rezipping.

**Comment by Gabrimax98** [comment]
You are a legend. Thank you for the tip on how to edit it!
I personally think it's better to add support to open/edit Clone.zip instead of the firmware name, cause AFAIK there are other models that use the same file structure as this one but are different models than the EE690DB i sent you.

Thank you again for your help, I really appreciate your time and effort on this!

**Comment by PredatH0r** [comment]
This is now implemented in version 2022-04-19
