### ISSUE TITLE
Can't open TLL file anymore after firmware upgrade - LG 55UB830V-ZG firmware version 04.11.13

### ISSUE THREAD

**Issue by poki2** [PredatH0r/ChanSort#3]
After the most recent update i can't open the TLL file anymore.
See file here http://ge.tt/7TGUapJ2/v/0?c

**Comment by PredatH0r** [comment]
It seems like this firmware update changed the binary TLL file format.
If you delete the binary TLL file (xxUB...TLL) from the stick, the TV will import the GlobalClone file, which can be edited with ChanSort.
