### ISSUE TITLE
Manually updating the reference list

### ISSUE THREAD

**Issue by quasarrete** [PredatH0r/ChanSort#303]
gb_astra28E_sky.txt reference list is outdated, is there any way we can manually update that? 
If you could please provide instructions on what those numbers mean (and where I can find those), I can take the time to update it if required. 
List seems to be from 2020 few channels missing and lot of them won't load.

**Comment by PredatH0r** [comment]
You can run a channel search on any TV, edit that list with ChanSort (optionally using the outdated list as a basis) and then select "File / Save reference list" and select the file type you want (e.g. *.txt) in the drop down list on the bottom.

The values in the .txt file are
ChNumber;Name;ONID-TSID-SID

ChanSort tries to find matching channels based on ONID-TSID-SID first, when applying a reference list. If no match is found, it tries to search by channel name.
