### ISSUE TITLE
Applying a reference list and get a blank window  supplied gb_astra282E_sky.txt)

### ISSUE THREAD

**Issue by swoodsy** [PredatH0r/ChanSort#304]
Hi, I'm using one of the supplied reference lists (gb_astra282E_sky.txt) 
I get this (supplied screenshot) when I try and use a reference list.  Can I do something to get this to work? Many thanks

![image](https://user-images.githubusercontent.com/8569272/186026689-efe81bbd-18da-488b-a75c-a2df1b3f68c1.png)

**Comment by damosullivan** [comment]
I have the very same issue

**Comment by PredatH0r** [comment]
Thanks for the information and reminder.
I was finally able to replicate the problem when running the program on a small screen in combination with a large Windows scaling factor. I will be fixed in the next release.

**Comment by PredatH0r** [comment]
Should be fixed since version 2022-10-06.
The dialog was redesigned to use separate pages for the steps to make it fit on small screens or screens with large scale factors.
If you still encounter issues, please reopen the ticket.
