### ISSUE TITLE
Channel list empty Samsung GQ43QN90A

### ISSUE THREAD

**Issue by rbike** [PredatH0r/ChanSort#310]
[Channel_list_T-NKM2DEUC-2101.0.zip](https://github.com/PredatH0r/ChanSort/files/9818427/Channel_list_T-NKM2DEUC-2101.0.zip)
When opening the attached file from a Samsung GQ43QN90A ChanSort doesn't find a channel list.

**Comment by PredatH0r** [comment]
I downloaded your file and opened the .zip file with the current version of ChanSort.
It shows me 221 DVB-C and 116 IP-TV channels.
Please be sure to open the .zip File directly with ChanSort and do not unzip it.

If you still encounter a problem, please reopen the ticket and provide detailed information to reproduce it.
