### ISSUE TITLE
ton fehlt, dienst nicht verfügbar

### ISSUE THREAD

**Issue by callamon** [PredatH0r/ChanSort#312]
Hallo,
vor einigen Tagen gab es hier eine Neusortierung der Fernsehsender, deshalb lief wieder einmal der Sendersuchlauf durch.
Anschließend habe ich diese Liste via USB-Stick auf den Desktop gebracht und mit ChanSort 2022-10-06 neusortiert. Dann wieder auf umgekehrten Wegen auf das Fernsehgerät (Samsung UE55U7500, akt. Firmware 1570) gebracht. Funktioniert so weit problemlos.
Jedoch werden einige Fernsehsender ohne Ton angezeigt (kein Mute!)
Bei einigen Sender schwarzes Bild mit dem Hinweise _Dienst nicht verfügbar_
Warum ist mir unklar.
Dann einmal den Fernseher zurückgesetzt und einen neuen Sendersuchlauf gestartet. Die zuvor betroffenen Sender haben jetzt Ton und sind plötzlich zu sehen. Nochmals die sortierte Liste über USB-Stick importiert. Leider wieder mit dem obigen Ergebnis.
Was habe ich da falsch gemacht?

**Comment by callamon** [comment]
Mittlerweile den dritten Versuch unternommen, der scheint geklappt zu haben.
Leider bin ich mir aber nicht im klaren, warum???

**Comment by PredatH0r** [comment]
Hier bin ich leider auch überfragt.
Was ich aber mit Sicherheit sagen kann, ist dass ChanSort nichts an den Tuner-Daten oder den ServiceID, Audio-PID, Video-PIC o.ä. innerhalb der Dateien ändert.
Je nach Empfangsart (Sat, Kabel, Antenne) kann in einer Samsung-Liste z.B. eine vordefinerte Länderliste gespeichert sein, z.B. als "Astra 19.2"-Liste anstatt einer neutralen "Sat"-Liste. Diese enthalten dann u.U. veraltete Daten, z.B. falsche Frequenz, oder Audio-PID, Video-PID, ...

Ich kann hier aber leider auch nur Vermutungen anstellen.

Ich schließen jedenfalls dieses Ticket, da das Problem vorerst gelöst sein dürfte.
