### ISSUE TITLE
Let us override this!

### ISSUE THREAD

**Issue by kronka** [PredatH0r/ChanSort#313]
`IMPORTANT: It is REQUIRED to select special options during the channel search on the TV. If you select a provider / country / satellite specific list, it will be pre-ordered and your TV will behave erratic after an export+import. Always select "none / other / all" and never your cable TV provider or something like "Astra 19.2E list" and blindscan.`

You need to let us override this and let us edit the "bad" lists anyway.
I fiddled half a day with my TV and found that I can't use the hard disk to record content or watch exxisting recordings if I don't select the country that I had set before.
I don't want to work through thousand channels on the tv, but as it is, that's my only choice.
I'd rather risk some erratic behavior.

**Comment by PredatH0r** [comment]
You do not necessarily have to use a neutral country setting, but at least you MUST NOT use a predefined channel list.
The TV's firmware is simply incapable of importing a list when it has a predefined list in memory.
It will randomly shuffle channels around, change numbers while you zap through them and all other kinds of craziness.

In the "Settings" menu you can set an option to allow editing such read-only lists. But it's unlikely that your TV will work as expected afterwards.

**Comment by kronka** [comment]
As soon as I select my country in the initial setup, I can only choose
between two setups, Astra and Sky, there is no other option. That "none"
option is only there if I select - - as country, which leads to the
mentioned recording restrictions.
I don't know if I could enable the option in the service menu? But I'll
check for that setting and still try with the predefined list. Thanks for
the fast feedback!

Horst Beham ***@***.***> schrieb am Mo., 31. Okt. 2022, 20:38:
