### ISSUE TITLE
ChanSort cannot import Loewe servicelist.xml

### ISSUE THREAD

**Issue by franck-888** [PredatH0r/ChanSort#317]
Hi,

Thanks for Loewe experimental support.
Unfortunately v2022-10-06 fails to import a Loewe list.
Please find attached a servicelist.xml showing that.
Though I am not sure it can help figuring out its underlying structure.

I wonder why Loewe uses such a complicated format for a simple channel list.
Other manufacturers, ex enigma2 based settopboxes, do that too :-(.
I dream about a simple channel list with 1 line/channel that could be handled by a plain text editor.
So thanks for your program that allows to handle such lists in a much easier way that the TV do.

[servicelist.txt](https://github.com/PredatH0r/ChanSort/files/9996047/servicelist.txt)    just rename .txt -> .xml   (github forbids .xml)
![error_import_servicelist](https://user-images.githubusercontent.com/107723864/201496533-f4a127d6-1041-4d08-84ab-053e79ddd030.png)

Kind regards,

**Comment by PredatH0r** [comment]
There should be a servicelist.db and a servicelist.xml file on the USB stick.
I don't own a Loewe TV, so I can't really tell if you have to select 2 different export options or if the TV should automatically export both files.
I received various exports which contained both files. The actual file used by the TV during the import is the servicelist.db, a SQLite database file. The ".xml" is more or less a text export of the data in the .db file.
ChanSort can edit the servicelist.db file.

**Comment by franck-888** [comment]
Thanks for your feedback.

Here are all the 4 files that get exported on USB stick:
```
$ file *
netconfig.xml:   XML 1.0 document, ASCII text, with very long lines, with no line terminators
servicelist.xml: XML 1.0 document, UTF-8 Unicode text, with very long lines
servicelist.xsl: XML 1.0 document, ASCII text, with very long lines, with no line terminators
settings.txt:    ASCII text
```
[channels.tar.gz](https://github.com/PredatH0r/ChanSort/files/10005184/channels.tar.gz)

generated by an (old) SL420 = bild 7, ca 2018, with latest available firmware = SL4xx_v5.4.1.0_20210816_production

ChanSort cannot open any of above 4 files.

Unfortunately there is no servicelist.db
I did not see an option in the TV to change the export format.

It would be perfectly understandable if ChanSort cannot load this old model. Maybe no need to spend time for it. You may close this ticket if you want.

BTW ChanSort proposes to open only a servicelist.xml for Loewe, no .db:
![import_formats](https://user-images.githubusercontent.com/107723864/201718085-31a70575-ed63-4b4e-8a49-77485daebf33.png)

Kind regards,

**Comment by PredatH0r** [comment]
Sorry, this was my mistake. There are so many file formats already that I start forgetting...

Some Hisense models use the same file format as some Loewe models, exporting both a .db (and sometimes a .xml file too).
But there are also some (older?) Loewe models that only export an .xml file.

Anyhow... the reason your file could not be opened is because of a bug in ChanSort.
A fixed version can be found on http://chansort.com/ChanSort_2022-11-14.zip

Please let me know if loading the changed list back into your TV actually worked.
(Try changing 1 or 2 channels at first to avoid wasting too much time in case the upload doesn't work)

**Comment by franck-888** [comment]
Yes ChanSort_2022-11-14.zip can successfully open the servicelist.xml
Unfortunately I will only be able to upload a modified list into Loewe TV in ca. 2 weeks.
I will let you know afterwards, please wait a bit.

**Comment by franck-888** [comment]
ChanSort_2022-11-14.zip works.
I could
- open servicelist.xml, without error
- swap the order of 4 satellite channels
- save the new servicelist.xml
- successfully import this modified servicelist.xml on the Loewe TV
Using the remote, I increased channel numbers on TV, starting before the swapped channels until after them, all fine.

As in the meantime someone already reorganized the channels via the TV, I won't need to use ChanSort this time => I won't test more deeply. Will probably happen at next TV channels cleaning 'opportunity'.

Thanks for your work.
Feel free to close this bug report if you already merged the fix.
