### ISSUE TITLE
Samsung Hotel TV Tizen HG50ET690U

### ISSUE THREAD

**Issue by nickkalsi** [PredatH0r/ChanSort#321]
Hi,
I am trying to edit the channel plan on a Samsung Hotel TV Tizen HG50ET690U using the latest ChanSort software.

1: From the Service menu, I select Clone from TV to USB
2: Once the configuration is copied to the USB, I then use ChanSort, by opening from the UBB d:\T-KTM2DEUCB\Clone\tvs-this
3: I can see two zipped folders; I select the folder tvs-chms
4: I can edit the channels once saved into the same file on the same USB
5: I then insert the USB into the TV and select clone USB to TV
6: I get the "The Clone package file on the connected USB flash drive is not valid check the file  and try again

I believe this is to do with the Tizen directory structure.

Your support will be appreciated.

Thanks
Nick
![9cf28d6f-8a78-42f1-ad1c-7cdfcbbedcfe](https://user-images.githubusercontent.com/60816147/203422363-7e67f0af-e384-425b-b89a-d749f2da3567.JPG)
![IMG-3618](https://user-images.githubusercontent.com/60816147/203422382-5e3c3775-c8f2-4fb3-8c1e-5738b78ce368.jpg)

**Comment by PredatH0r** [comment]
I don't have any experience with hospitality TVs so far, but if you can send me the complete content of the USB stick as a .zip to horst at beham dot biz, I will try to find out what's different there compared to normal consumer models.

**Comment by nickkalsi** [comment]
Hi Benham,
Thanks for the quick response,

Please see the attached zip file. You can delete a channel and send it back
to me so I can try if that works.

Regards
Nick

**Comment by PredatH0r** [comment]
Hi Nick!
Unfortunately replying to a github generated email does not work with attachments.
Please upload the file to the github web page or send it to my personal email address horst -at- beham -dot- biz.

**Comment by nickkalsi** [comment]
Uploaded
Thanks

**Comment by PredatH0r** [comment]
Thanks!
My first guess is that the file "validate.txt" in the root folder contains a checksum over one or more of the other files.
If so, any changes made to the other files would require calculating a new checksum and write it to the file. And the prize question then is how to calculate that checksum.

To see if this is really the case, can you try and make a fresh export to a USB stick, open the validate.txt file with a text editor and change any digit in it, save it and try to import the stick back in the TV.

Maybe a step "0" before this would be to re-import a completely unmodified stick. Just to rule out issues with the stick. Some TVs are picky about the size (should be <= 16GB) or the file system format (should be FAT32 and not NTFS).

**Comment by nickkalsi** [comment]
exported file from TV
[validate.txt](https://github.com/PredatH0r/ChanSort/files/10074897/validate.txt)
content in file 2963978954

After making the change to the channel plan
Content in file 2963978954
[validate.txt](https://github.com/PredatH0r/ChanSort/files/10074917/validate.txt)

I also tried a FAT USB2=8GB instead of a Fat USB3 = 32GB

**Comment by nickkalsi** [comment]
Hi, I tried an alternative method using the Service menu, Channel setup, Expert settings, Transfer channel list, PIN NUMBER, and Export to USB. I made channel changes using ChanSort. Saved changed on USB. 

Followed the same procedure above using Import from USB; this worked - Bingo

Thanks for your support
Nick.
