### ISSUE TITLE
channel list lg television

### ISSUE THREAD

**Issue by nervo1** [PredatH0r/ChanSort#322]
i have .TTL file of a lg television but chansort cannot open it
program give this message "not plugin found to read/write xxxxxx.TLL file

**Comment by PredatH0r** [comment]
Please attach your channel list file.
There is a long list of different TLL file formats and I need the file to be able to investigate.
Regards,
Horst

**Comment by nervo1** [comment]
hi....thank you for your reply.....i downloaded wrong file from my lg television .....just now I downloaded the right one and the program opens and works well......I made a mistake .......grazie
