### ISSUE TITLE
 Can't load xml from Sony XR-55A80J

### ISSUE THREAD

**Issue by DG7YEO** [PredatH0r/ChanSort#328]
Hi,
when I try to load the sdb.xml from my Sony XR-55A80J (Google TV) I get the error message below:
`Invalid Binary TLL file format. mayby a GlobalClone/XML file?`

No clue what that mean, I tried already 2 different USB Stick to exclude an issue with the Stick. 
No problem to load the xml to the Sony Channel Editor but this software is .....

Any hints welcome.

Elmar

**Comment by PredatH0r** [comment]
thanks for the feedback.
It's now fixed in https://github.com/PredatH0r/ChanSort/releases/tag/v2022-12-04

**Comment by DG7YEO** [comment]
Thank you for fast fixing, now it works perfekt.
