### ISSUE TITLE
Problem with the scm file

### ISSUE THREAD

**Issue by przemo31** [PredatH0r/ChanSort#33]
Hi.
I have a problem with the scm file.
Everything was good on version 2015-11-27.

[20160802.zip](https://github.com/PredatH0r/ChanSort/files/396952/20160802.zip)

**Comment by PredatH0r** [comment]
The problem is that you renamed the file.
ChanSort tries various methods to determine the format of the file, one of them is using the file format version number that is part of the original file name. It's not always possible to correctly detect the format based on whatever is inside the file.

**Comment by przemo31** [comment]
Ok. Thanks :)
