### ISSUE TITLE
DVB-C channel lists (TechniSat DVB-C .DBM file)

### ISSUE THREAD

**Issue by APMichael** [PredatH0r/ChanSort#334]
Attached are two ZIP files with DVB-C channel lists from a cheap TechniSat and Xoro receiver. (Presumably, the formats will also be used in many other cheap receivers.) If you ever have a few free minutes, you might want to take a look at the files. Many thanks in advance.

[TechniSat-DVBC.zip](https://github.com/PredatH0r/ChanSort/files/10303228/TechniSat-DVBC.zip)
[Xoro-DVBC.zip](https://github.com/PredatH0r/ChanSort/files/10303229/Xoro-DVBC.zip)
[current_sorting.txt](https://github.com/PredatH0r/ChanSort/files/10303250/current_sorting.txt)

**EDIT:** If someone is interested in the now supported TechniSat model: "TechniSat HD-C 232" (it is still being sold).

**Comment by PredatH0r** [comment]
Thanks for your files.

The Xoro files are unfortunately encrypted, so there is no chance to do anything with them. (Other TVs/receivers also export .sdx files, but those are unencrypted and can be edited)

The TechniSat file is readable and its .DBM format seems to be similar to what some Xoro and Strong DVB-S receivers use.
But like all undocumented binary formats, it is very tedious, error prone and time consuming guessing what each byte in the file actually means. 
Do you have a URL to your cable provider's official channel list (PDF or so) that also includes information like frequency, service-id, video-PID or the like? That would make the analysis a lot easier.

**Comment by APMichael** [comment]
Thank you very much for your reply and checking the files.

Too bad that the files of the Xoro are encrypted. One really wonders what motivates a manufacturer to encrypt something as trivial as a channel list? I guess we don't have to understand... 😄

Unfortunately, the only website I know with such detailed information about the channels no longer exists since mid-2021. However, I still have a reference list of ChanSort from another TV here. Is the data contained in it sufficient for this?

[vodafone.txt](https://github.com/PredatH0r/ChanSort/files/10345949/vodafone.txt)

**Comment by APMichael** [comment]
I have found a new website:
https://helpdesk.vodafonekabelforum.de/sendb/belegung.html

Please select the following:
**Bundesland** > `Baden-Württemberg`
**Netz** > `Heilbronn`

When the channel list is displayed, the following option can be selected:
**Einstellungen** > `SID, PIDs und Bouquet (Expertenmodus)`

Then very detailed information about the channels will be displayed.

**Comment by PredatH0r** [comment]
Hi Michael,

Ich mach mal auf deutsch weiter. Danke für die Zusatzinfos, ich konnte damit schon einiges entziffern.
Bevor ich aber weiter machen kann, stellt sich eine entscheidende Frage. Und zwar, ob die Datei mittels Prüfsumme vor ungewollten Änderungen (bzw. Datenfehlern) geschützt ist oder nicht.

Ich habe deine Datei manuell verändert und RTL und SAT.1 vertauscht (sind jetzt auf 4 und 3 statt 3 und 4).
Wenn dein TechniSat die Datei einliest und die Programme dann auch so belegt sind, kann ich weiter arbeiten.

Es kann aber durchaus sein, dass die ersten beiden Bytes in der Datei eine Prüfsumme sind. Die müsste ich dann entsprechend mitändern, weiß aber nicht wie diese berechnet wird. Keine der gängigen Methoden hat mir diese dort gespeicherte Zahl geliefert.

[vodafone-edited.zip](https://github.com/PredatH0r/ChanSort/files/10346633/vodafone-edited.zip)

Beste Grüße,
Horst

**Comment by APMichael** [comment]
Hallo Horst,

wow, das ging ja schnell! 👍 Klasse, dass Du alles herausfinden konntest, was für die Bearbeitung der Datei nötig ist.

Ich habe die von Dir geänderte Datei trotzdem mal ausprobiert und kann berichten, dass diese erfolgreich importiert wurde und der Tausch der beiden Sender funktioniert hat. (Die Prüfsumme könnte daher eventuell erst bei größeren Änderungen, wie z.B. Löschen von Sendern, eine Rolle spielen?)

Nochmals vielen Dank für Deine Mühen. Ich freue mich auf die zukünftige ChanSort-Version mit Unterstützung dieser TechniSat-DBM-Datei, auch wenn es etwas länger dauern sollte.

Viele Grüße,
Michael

**Comment by PredatH0r** [comment]
Hallo Michael,

deine Liste sollte jetzt mit https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-06 bearbeitet werden können.

**Comment by APMichael** [comment]
Hallo Horst,

Tausend Dank für die superschnelle Umsetzung. Das Sortieren der Sender und Importieren der Senderliste in den TechniSat funktioniert fehlerfrei. 😃

Wäre es noch möglich die Unterstützung für die Kanaloptionen (Gesperrt, Überspringen, Versteckt und Favoriten) hinzuzufügen? Ich habe eine neue Senderliste angehängt, mit den folgenden Optionen:

RTL = Überspringen
SAT.1 = Gesperrt
ProSieben = Versteckt*
kabel eins = Favoriten A: Film
RTLZWEI = Favoriten B: Nachrichten
VOX = Favoriten C: Sport
Tele 5 = Favoriten D: Musik

\* Bei "Versteckt" ist mir folgendes aufgefallen: Im TechniSat wird dies "Löschen" genannt. Der Sender wird danach ganz ans Ende der TV-Sender verschoben und wohl mit einem entsprechenden "Status-Byte" versehen.

Zudem ist es wichtig, dass die Reihenfolge von TV und Radio streng eingehalten wird, das bedeutet, dass immer zuerst alle TV-Sender und danach alle Radio-Sender in der Liste stehen müssen. Mit einem Vermischen kommt der TechniSat nicht klar. Ich weiß nicht, ob so etwas leicht umsetzbar ist, wenn nicht, würde eventuell auch eine Textmeldung mit diesem Hinweis ausreichen.

Danke und Gruß,
Michael

**Comment by PredatH0r** [comment]
Neue Version auf https://chansort.com/ChanSort_2023-01-06.zip (die ist noch nicht auf der github Webseite, da ich noch ein paar andere Änderungen teste).
Damit kann man jetzt die Kennzeichen setzen.

"Versteckt" verschiebe ich nicht automatisch nach hinten. Ich kann da keine TechniSat spezifische Logik einbauen, die dann für alle anderen Geräte ein Problem macht. Ich vermute der Receiver macht das, weil man sonst ein Loch in den Nummern hat beim Zappen.

Das mit Radiosendern nach TV-Sendern konnte ich noch nicht einbauen, werde das aber noch machen.
Die gleiche Einschränkung gibt's auch bei manchen anderen Senderlistenformaten, wo es auch noch nicht geprüft wird.

**Comment by APMichael** [comment]
Das Anzeigen der Kennzeichen, welche über den TechniSat gesetzt wurden, funktioniert.

Leider werden jedoch neue, direkt über ChanSort gesetzte Kennzeichen nicht in der Datei gespeichert. Werder der TechniSat erkennt diese, noch ChanSort (nachdem die Datei neu geladen wurde).

**Comment by PredatH0r** [comment]
Danke für's schnelle Testen.
War mein Fehler ... hatte vergessen die Kennzeichen zurück in die Datei zu schreiben.
Das oben gelinkte .zip ist jetzt aktualisiert.

**Comment by APMichael** [comment]
Hallo Horst,

super, jetzt funktioniert alles wie vorgesehen! 👍 🎉

Das Kennzeichen "Versteckt" scheint vom TechniSat zwar wirklich nur korrekt umgesetzt zu werden, wenn sich die Sender am Ende der TV-Liste befinden, aber das lässt sich leicht manuell bewerkstelligen. Daher bin ich nun rundum glücklich mit der neuen Version. 😃

Nochmals ganz vielen Dank für Deine schnelle Unterstützung und Umsetzung! Falls ich noch irgendetwas testen kann/soll, bitte einfach melden.

Viele Grüße,
Michael
