### ISSUE TITLE
LG 55US662H9ZC

### ISSUE THREAD

**Issue by propheta** [PredatH0r/ChanSort#340]
I recently bought 2 LG TVs and when I tried to edit the channels I get an error when opening the file generated by the TV.

No plugin found to read/write C:\TV\xxUS662H9ZC.TLL

Ill attach the channel file
[xxUS662H9ZC_9.TLL.zip](https://github.com/PredatH0r/ChanSort/files/10401352/xxUS662H9ZC_9.TLL.zip)

I dont know if its a file issue. The TV has firmware 4.64.40

**Comment by PredatH0r** [comment]
I can open your .TLL file without problems.
What version of ChanSort did you use? (the number/date can be found in the window title)
The latest official version can be found here: https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-10

There will most likely be another update today or tomorrow, but with nothing that affects LG lists.

**Comment by propheta** [comment]
I’m using the latest version available. Files from older tvs can be opened without problem. Is there any recommendation for where the program should be unzipped?

Regards,
Gabriel Bolea
________________________________

**Comment by PredatH0r** [comment]
Location shouldn't matter. 
I downloaded the official .zip now in a virtual machine that doesn't have any development tools installed.
My suspicion was that a required DLL might have been missing, but that doesn't seem to be the case.
There were no issues to open your file.

![image](https://user-images.githubusercontent.com/6238104/212072127-8d285d72-97c9-4939-9c7e-54aade236d20.png)

One thing that might cause it, is some 3rd party anti-virus tool or strict windows security settings that block DLLs that were downloaded from the internet.
If you use 7-Zip to extract ChanSort, the files won't have that "downloaded from internet" tag.
Extracting with Windows Explorer or WinZip does set that flag.
On my machine I only use the standard windows defender. Both 7-Zip and Explorer's "Extract all" worked fine to load your file.

**Comment by propheta** [comment]
Ok I’ll give it a try and see. I’m also on an Windows 11 VM on a mac, as it’s ARM version shouldn’t be any issue also, right?

Cumprimentos,
Gabriel Bolea
________________________________

**Comment by propheta** [comment]
Ok so little update. I extracted the zip file with 7zip at C:\ChanSort. Looks like now I can open the file. Thank you for your help.

From: Horst Beham ***@***.***>
Date: Thursday, 12 January 2023 at 13:23
To: PredatH0r/ChanSort ***@***.***>
Cc: Gabriel Bolea ***@***.***>, Author ***@***.***>
Subject: Re: [PredatH0r/ChanSort] LG 55US662H9ZC (Issue #340)

From what I could find, that DLL should work just fine with ARM too.
I have a m1-MiniMac standing around and will try to set up VirtualBox and Windows 11 on it over the weekend to see if I can replicate the problem there.

**Comment by propheta** [comment]
I’m using Parallels Version 18.1.1

From: Horst Beham ***@***.***>
Date: Thursday, 12 January 2023 at 16:14
To: PredatH0r/ChanSort ***@***.***>
Cc: Gabriel Bolea ***@***.***>, Author ***@***.***>
Subject: Re: [PredatH0r/ChanSort] LG 55US662H9ZC (Issue #340)

Thanks, that's great news.
I'm currently in the middle of installing Win11-ARM on my m1 MacMini for testing.
Just out of curiosity, what VM System are you using?
VirtualBox was a dead end, now I'm trying TM, which seems to work fine so far.
