### ISSUE TITLE
Problem with Samsung QE43Q60BAUXXN

### ISSUE THREAD

**Issue by tommyinfo** [PredatH0r/ChanSort#348]
Hi
My problem is when i Import file zip modify by chansort, my tv said succesfully chaine list but when my tv restart i have 0 chainnel list, i only have ip channel
I use astra and eutelsat sat 
Maybe i miss something important 
if someone have the answer , i take it
[Channel_list_T-NKLBDEUC-1403.6.zip](https://github.com/PredatH0r/ChanSort/files/10734761/Channel_list_T-NKLBDEUC-1403.6.zip)

**Comment by PredatH0r** [comment]
Is this the original List from the TV or the already modified list?
So far I am not aware of any issues with Samsung TVs and ChanSort. 
For further analysis I'd need the original file (which ChanSort saves as .bak) and the modified file. 
Please also take the modified file directly off the USB-Stick to make sure I can see exactly what the TV loads (in case the stick is damaged).

Did you use a FAT32 formatted stick for the data transfer? 
TVs sometimes have problems with NTFS sticks or ones larger than 16GB.

**Comment by tommyinfo** [comment]
Hello
I use a 1go usb formatted at FAT32
My TV is QE43Q60BAUXXN
And i also saw a problème on chansort, when i open this file on samychan.com i have 1257 channel sattelite but with chansort i only have 139 channel
[Channel_list_T-NKLB
[bakChannel_list_T-NKLBDEUC-1403.6.zip.zip](https://github.com/PredatH0r/ChanSort/files/10791707/bakChannel_list_T-NKLBDEUC-1403.6.zip.zip)
DEUC-1403.6.zip](https://github.com/PredatH0r/ChanSort/files/10791676/Channel_list_T-NKLBDEUC-1403.6.zip)

**Comment by tommyinfo** [comment]
Everything works for me , it was my usb-stick the problem
i change it with a 32 go
your software is awesome
Thank you for the reply
