### ISSUE TITLE
LG favorite lists

### ISSUE THREAD

**Issue by Henry2o1o** [PredatH0r/ChanSort#384]
LG favorite lists are not transferred by name to the TV, WEBOS4.

Existing ones remain.  How could the problem be solved?

**Comment by PredatH0r** [comment]
The LG webOS 4 format does not contain any names for favorite lists.
There is only data labeled as "favoriteIdxA" to "favoriteIdxH" and ChanSorts shows those as lists "Fav A" to "Fav H" (actually H was missing, but that will be fixed now).

Unfortunately there is no way for ChanSort to change the favorite list names for webOS4.
