### ISSUE TITLE
[2023-12-18] Error while exporting print preview to pdf - missing DevExpress.Pdf.v23.1.Core DLL

### ISSUE THREAD

**Issue by Kogl1n** [PredatH0r/ChanSort#389]
version: 2023-12-18 release
error type: missing dll
steps for reproduction: File->Print->Preview->File->Export Document...->PDF File->OK->Save

There are two error message windows (one titled 'preview' opening in the foreground and one 'error at runtime'(?) opening in the background). The application crashes after closing the latter one.

Edit: The same problem exists for other file exports.

**Comment by PredatH0r** [comment]
Thanks for pointing this out.
I added the required DLLs for the PDF export to ChanSort 2023-12-31.
The Word export is the only one that isn't working in this release as it would require adding another 12MB of DLLs.
