### ISSUE TITLE
Edit audio column

### ISSUE THREAD

**Issue by Pierhagi** [PredatH0r/ChanSort#398]
Hi everyone,
is it possible to change the value of the Audio ID column?

**Comment by PredatH0r** [comment]
Unfortunately not.
It's simply not feasible to add support for modifying tuner data for several dozen file formats. 
The amount of work, the lack of technical documentation of the file formats and the lack of test devices makes it as good as impossible to do so.
Therefore I will keep ChanSort restriced to only modify channel numbers, channel names and favorites. And that alone already requires lots of special handling for the different capabilities of the various supported devices and formats.
