### ISSUE TITLE
LG file format not recognized

### ISSUE THREAD

**Issue by AleoDan** [PredatH0r/ChanSort#399]
The channel list file format exported from LGs with firmware 04.40.90 is not recognized anymore.

**Comment by PredatH0r** [comment]
Can you please send me such a file so I can take a look?
(It's also possible that the TV wrote garbage data to the stick, especially if it was formatted with NTFS or >32GB)

**Comment by AleoDan** [comment]
It is OK. The new firmware did not write anything on TV->USB until I imported back the list USB->TV. Strange. It is recognized now. I will close the issue.

**Comment by AleoDan** [comment]
Strange new firmware, but is working.
