### ISSUE TITLE
HISENSE Channel.db not readable

### ISSUE THREAD

**Issue by acerhorn** [PredatH0r/ChanSort#41]
Hi Team, 
I'm trying to sort the channels of my new HISENSE H65MEC5550.
I get the attached MessageBox. Any help available?

Thanks and regards!
Andreas

[error.pdf](https://github.com/PredatH0r/ChanSort/files/496342/error.pdf)

**Comment by PredatH0r** [comment]
Hi Andreas!
Could you please send me your channel list file?
Did you get that messge when loading the file, when using "Save" or when using "Save as"?
"Save" should always work, "Save as" might have problems with specific file formats.

**Comment by acerhorn** [comment]
Hi Horst!
The error reported happened under Win7. 
In the meantime I tried it under Win10 and here it worked like a charm. I successfully sorted my channels. 
Thanks for your help.
Andreas
