### ISSUE TITLE
Tornado 32ES9300E-A Smart TV.

### ISSUE THREAD

**Issue by mmmmm-sbi** [PredatH0r/ChanSort#414]
![image](https://github.com/PredatH0r/ChanSort/assets/58107773/15072c07-22e3-4897-aac1-d737f932100d)
Dear Team,

I am encountering an issue with my Tornado 32ES9300E-A Smart TV. When I export the channels to my USB drive, I find ten different files, and I am unsure which one to use to rearrange my channel list.

Additionally, I am experiencing difficulties with the software update for the same TV model. I have been unable to successfully update the software.

Could you please provide guidance or a solution for these issues?

_Originally posted by @CompuMohssen in https://github.com/PredatH0r/ChanSort/issues/410#issuecomment-2208698691_

**Comment by CompuMohssen** [comment]
Dear Team,
I wanted to ask if my Tornado 32ES9300E-A TV is now supported by the latest version of ChanSort for channel management. I'm experiencing issues with exporting and rearranging the channels on my TV, and I want to ensure that the current version of ChanSort can handle my TV model. Could someone please confirm if this TV model is supported and if there are any specific steps I need to follow?

Thank you in advance for your help!

**Comment by PredatH0r** [comment]
I do not have access to any Tornado TV, so I can't give any guidance about channel management on those.

ChanSort supports editing a file named \_\_chtb\_do\_not\_delete\_.xml, which was exported on a Tornado 32ES1500E and sent to me. I do not know if you model uses the same file or a different kind of list. Very often "Brands" just buy hard- and software from different OEMs and put their sticker on it. As a result they export all sorts of files with no consistency whatsoever. Prime example is Philips and that Tornado 32ES1500E was using a similar format than some Philips models.
