### ISSUE TITLE
Philips TV

### ISSUE THREAD

**Issue by PatlaBarod** [PredatH0r/ChanSort#421]
Hello while using your app I have encountered the following difficulties. I don't have some channel names displayed, they are probably written in Russian (Cyrillic). I have attached a file with the list of channels.
P.S. Exactly the same list of channels, but from Samsung TV displays without problems.
![Скриншот 19-08-2024 215154](https://github.com/user-attachments/assets/b9941cce-7491-47f0-8123-00eaa336377a)

[Clone.zip](https://github.com/user-attachments/files/16664163/Clone.zip)

**Comment by PredatH0r** [comment]
Thanks for your feedback and my apologies for the late reply.
I was able to find a solution that's included in ChanSort 2024-10-01 that will be released within the next hour

**Comment by PredatH0r** [comment]
https://github.com/PredatH0r/ChanSort/releases/tag/v2024-10-01
