### ISSUE TITLE
Sortierung DBM Datei (Strong SRT 7007)

### ISSUE THREAD

**Issue by uChoh5fe** [PredatH0r/ChanSort#427]
Hi,

erstmal vielen Dank fuer das geniale Programm, erspart enorm viel Tipparbeit auf der Fernbedienung :-)

Mein Problem ist, das ich zwar die Kanaele sortieren und abspeichern kann, aber auf dem Receiver sind sie trotzdem noch verkehrt. Wenn ich dann die Datei nochmals lade, kommt ja die Abfrage der Sortierung, da ist die Reihenfolge so wie ich sie am Receiver sehe

![c1](https://github.com/user-attachments/assets/ddee7fc7-8313-419c-8327-f7aa4ec515b9)

nach der Bestaetigung mit der vorhanden fortzufahren und weiterzusortieren, wechselt die Ansicht in die von mir gewuenscht.

![c2](https://github.com/user-attachments/assets/905c1003-2d22-4cde-8fc3-7ddfef89a8a9)

Any hints? Anbei die DBM Datei.

Nochmals Danke und Gruss

[HB_DATABASE_10_27.DBM.zip](https://github.com/user-attachments/files/17541217/HB_DATABASE_10_27.DBM.zip)

**Comment by PredatH0r** [comment]
Danke für die Info.
Direkt nach dem Laden der Datei zeigt ChanSort die Sender in der selben Reihenfolge an, wie sie physisch hintereinander in der Datei stehen. Jeder Senderdatensatz enthält aber auch eine Zahl für die Programmnummer, und nur diese ändert ChanSort derzeit. Nach der Auswahl "Bestehende Liste bearbeiten" wird die Liste auch nach genau dieser Nummer sortiert.

Anscheinend ignoriert dein Receiver diese Nummer und geht rein nach der Datensatzreihenfolge vor. Aber das ist auch nur geraten.

Kannst du mir bitte 2 von deinem Receiver exportierte Dateien schicken: 
Die erste direkt so wie sie jetzt im Receiver ist, dann 2 Sender über das Menü des Receivers vertauschen und nochmal exportieren?
Ich kann dann im Vergleich der beiden herausfinden, was genau sich geändert hat und sicherstellen, dass ChanSort ebenfalls so vorgeht.

Besten Dank,
Horst

**Comment by PredatH0r** [comment]
Auf https://chansort.com/ChanSort_2024-10-28.zip liegt jetzt eine Programmversion, die auch die Datensätze umreiht. Vielleicht funktioniert es damit. LG, Horst

**Comment by uChoh5fe** [comment]
Hi Horst,
deine Vermutung hat sich bestaetigt. Mit der Version 2024-10-28 wird die Senderliste nicht nur am PC sondern auch am TV richtig angezeigt :-)

Vielen Dank nochmal!
