### ISSUE TITLE
Problems with Samsung J and Favourites

### ISSUE THREAD

**Issue by HenryLoenwind** [PredatH0r/ChanSort#5]
http://loenwind.info/channel_list_UE32J5170_1201.zip

When I import the sorted file (..._in) the TV will display *all* channels in *all* Favorite lists. They are ordered "Analogue channels, correct channels (in program number order), page break, other digital channels (in program number order)". When exporting the list again (..._reexport), channels that have been watched show up as "A, B, C, D, E", others remain as imported.

**Comment by yusufbozar** [comment]
I used ChanSort 2015-09-19 version. I ordered channel list Then i tried to pass favorites, tv, radio and all (channels) Yes i could choose  but it doesn t remember my choose. for example i choosed radio but when i opened channel list it is opening all channel list again.  SAMSUNG J series

**Comment by PredatH0r** [comment]
Thanks for your report and my apologies for the late response.
I was able to reproduce it and fixed it for the next version (>= 2015-11-28)

**Comment by HenryLoenwind** [comment]
Thx, and no need to apologize.
