### ISSUE TITLE
Open a zip, save a scm

### ISSUE THREAD

**Issue by Izze70** [PredatH0r/ChanSort#52]
Hi,

I have a problem, I open a channellist export as a zip file from a newer Samsung TV (K-series) and want to to save a .scm for an older Samsung (H-series) TV so that I dont have to do the work of sorting channels twice.
How do I do that?

Thanks,

Izze

**Comment by PredatH0r** [comment]
ChanSort cannot convert file formats, but it supports reference lists.
Make a full channel search on your H-series model, export the file on USB, open it with ChanSort and select the already sorted file from your K-series model as the reference list to copy the channel numbers and favorites.

**Comment by Izze70** [comment]
Ah, OK, thank you for the hint.
I always opened an old scm and wanted to "import" the new zip and expected that the new list will just overwrite the old scm.

Thank you!
