### ISSUE TITLE
Support for Sony TV?

### ISSUE THREAD

**Issue by BDein** [PredatH0r/ChanSort#58]
Hello Guys,

Great project:-)
Are there any chance of adding support for Sony TV's?

PS. It's an XML file, and I've attached a copy.

Best Regards

Bjarne

[sdb.zip](https://github.com/PredatH0r/ChanSort/files/752546/sdb.zip)

**Comment by Scoty43** [comment]
I hope its coming for Sony TV. I like this Tool and miss on my new Sony TV. Here also my sdb.xml. Please remove the zip on the end.


![sdb xml](https://cloud.githubusercontent.com/assets/25227541/25315475/90401df6-2855-11e7-9bfd-0b06578cf2c1.jpg)

**Comment by PredatH0r** [comment]
Currently I don't have time to add support for Sony.
Since I also don't have a Sony TV, it would be quite a tedious task to get this working.
And I haven't figure out yet how to calculate the checksum inside the file. Without it, the TV would refuse the load the file.

**Comment by PredatH0r** [comment]
Sony support added to https://github.com/PredatH0r/ChanSort/releases/tag/v2019-07-16
