### ISSUE TITLE
Support for Samsung K-Serie ?

### ISSUE THREAD

**Issue by denisblau** [PredatH0r/ChanSort#59]
I can not open the Samsung K-5579 channellist in ChanSort ?

**Comment by PredatH0r** [comment]
I haven't received any files from a K-series model so far, so I can't tell whether it is using the same format as the J-series (in which case it would be supported) or a different (unsupported) format.

**Comment by igbor** [comment]
I can send you a data file from Samsung UE65KS8005. Tell me how I can do this.

**Comment by igbor** [comment]
List of channels of the TV operator Uricon Tricolor UE65KS8005
https://www.dropbox.com/sh/ky8u63x5j60v99x/AACaCS6DldQMJ9eu0TgF6kAoa?dl=0

**Comment by PredatH0r** [comment]
Thank you for the test file igbor.
I just open the file successfully with ChanSort 2017-11-16.
@denisblau: if your file cannot be opened, please send me the file for further analysis
