### ISSUE TITLE
Merge/Join two files

### ISSUE THREAD

**Issue by brisel1** [PredatH0r/ChanSort#62]
Please, can you make an option to copy/paste channels or merge/join two files...

**Comment by yuanxin69** [comment]
where？

**Comment by brisel1** [comment]
In chan sort, it is more easily to copy from another chan  sort list than from reference list.

**Comment by PredatH0r** [comment]
Such a feature will never be supported in ChanSort.

ChanSort supports dozens of file formats and I knows just enough about these formats to manipulate program numbers and favorites.
Adding chanels requires in-depth knowledge of these file formats that only the TV firmware programmers have. And it would be an astronomical amount of work to support that.

What you can do in ChanSort is run a full scan on your TV, open then file in ChanSort and select another file as a reference list to apply the same channel order.
