### ISSUE TITLE
missing testfiles

### ISSUE THREAD

**Issue by FroggieFrog** [PredatH0r/ChanSort#67]
Can you please add the testfiles so anyone can run the (existing) unittests?

**Comment by PredatH0r** [comment]
I added the files for Test.Loader.Samsung project to git.

I don't want to add the files in the directories iterated in Test.Loader.LgTest, as they contain user names and maybe other personal settings of these users. There aren't any real assertions for those, other than "no unexpected exceptions".

If you want, you can send me an email, I'll upload the files to a private server and send you the download link.
