### ISSUE TITLE
Crypt channels not showing on TV - Samsung H series

### ISSUE THREAD

**Issue by FilipeAmadeuO** [PredatH0r/ChanSort#69]
Hello
I have a recente problem after some changes from my provider. Now all the crypt channells show on ChanSort but not on TV.
Can you please check the problem ?

Also can you add the possibility to check/unckeck the crypt flag ?

Thanks

Both lists: new -> does not show crypted channels
[channel_list_UE40H6200_1201.zip](https://github.com/PredatH0r/ChanSort/files/1366757/channel_list_UE40H6200_1201.zip)

**Comment by PredatH0r** [comment]
Can you please provide me some additional information?
Your cable TV provide made some modifications.
Did you run a channel search after that, exported the new file and tried to edit it with ChanSort?
Were you able to see the crypted channels on your TV after the search (before importing a modified list)?

Many TVs have an option for the channel search whether or not encrypted channels should be included.
I don't own a Samsung H TV, so I don't know how the menu works. Is there an option maybe that would hide encrypted channels?

The next update (probably released later today) will allow changing the Crypt flag for .scm files.
I'm not sure though if this will help in your case.

**Comment by FilipeAmadeuO** [comment]
Yes. Of course. My cable TV made some modifications and now the crypted channels are not shown anymore on Samsung channel list.
If i run a complete channel search i get all channells (crypted+not crypted) but for some reasons they are shows on ChanSort but not on TV. There is no option to hide crypted channels.
I attach both lists. Before providers changes and after for you to see if you can check any changes.

**Comment by FilipeAmadeuO** [comment]
https://www.dropbox.com/s/5nsyemmx4s4lj44/channel_list_UE40H6200_1201.zip?dl=0

**Comment by FilipeAmadeuO** [comment]
Hi PredatH0r
Any chance to take a look on the chanell files ? 
There is probably another flag (not in Chansort) that hides those channels...

**Comment by FilipeAmadeuO** [comment]
Hi PredatH0r
Can you please take a look on the files attached on the first post:
channel_list_UE40H6200_1201.scm -> Crypted channels show on Samsung TV List
channel_list_UE40H6200_1201_new.scm -> Crypted channels not show on Samsung TV List

The problem is on the map-CableD file. Because if i replace the map-CableD in the old version, TV does not show crypted channels.

**Comment by KanalDecode** [comment]
Hi,
Try this:
In map-CableD, after Qam change from 01 to 00
Before Symbol rate change 01 01 00 00 to 01 00 01 00
Then calculate checksum.

**Comment by FilipeAmadeuO** [comment]
Do you suggest any software for editing ?

**Comment by FilipeAmadeuO** [comment]
Hi
Do you suggest any software for editing ?
Thanks

Filipe Alves


No dia 27/10/2017, às 20:18, KanalDecode <notifications@github.com> escreveu:

**Comment by KanalDecode** [comment]
I used HxD.exe "hex editor" to change and calculate the new checksum.
ChanSort developers can use this information to change app.
Most of those flags are not known in "scm-map-Digital.h"

Regards,
KanalDecode

**Comment by FilipeAmadeuO** [comment]
Hi. I tried but i have "knowledgement limitations :) "
I can find and change 01 01 00 00 to 01 00 01 00 but not the Qam change from 01 to 00 change. 
Also i do not sure how to correct checksum in HxD.
I attach a file. Channel list from the beginning of file (first 10 channells):
- List Ok -> AMC HD; Sport TV+ HD;  Sic Noticias HD; Radio Lusitania; TSF; Super FM 
- List NOK -> TVCine 4 HD; Discovery HD Showcase; Odisseia HD; TVCine 1 HD; 
Can you please change some channells flag so i can check which change(s) makes any effect ?

[map-CableD.zip](https://github.com/PredatH0r/ChanSort/files/1424102/map-CableD.zip)

**Comment by PredatH0r** [comment]
Hi Filipe and KanalDecode!
I haven't had any time to modify ChanSort lately, but I'm currently looking into this.
@KanalDecode, can you tell me what the meaning of these bytes is?
Most TVs have a flag to hide channels, but I don't know where this is stored in the map-CableD data records. Is the "Unknown13" (after "Qam") this "Hidden" flag?
The "01 01 00 00" before the symbol rate are fields for "encrypted", "frame rate", and 2 unknowns ("Unknown26"). Since 01 doesn't seem like a plausible value for a frame rate, I guess I got something wrong there.
@Filipe: if you're willing to run some experiments, i have created [test files](http://tox.beham.biz/permutations.zip) with various permutations of the fields that were different between your old and new list. The channel #19 "Sport TV 1" is the one I modified there.
I suggest to try the 0_1010 file first. It has identical values as your old list and is expected to work.
Then try 1_1010. If that also works, we can conclude that the first field doesn't matter at all.
Then you can try 0_1000 and 0_1110 if those work too. If so, we know that only the first field matters and the others don't.
The other 1_ files are just there for completeness and don't have to be tested at this point.

**Comment by FilipeAmadeuO** [comment]
I tried but in all list when i try to import to TV i get "Invalid Channel List" message.
Any idea ?

**Comment by PredatH0r** [comment]
I'm so sorry. I only modified the data fields and forgot to update the checksums.
I'll be preparing a new set of files. I hope I get them ready by tomorrow.
Thank you so much for your help!

**Comment by FilipeAmadeuO** [comment]
Many thanks :)

**Comment by KanalDecode** [comment]
Hi PredatHOr,

I dind't have much time to investigate.
I don't know, but to un-hidden you need to have "Unknown13" = "00" and "frame rate" = "00".
Unknown26 no need to change, but HD without Cript have "00 00 **01 00**".

01 Crypt
00 un-hidden
01 ?
00 ?

Best regards,
KanalDecode

**Comment by KanalDecode** [comment]
Hi PredatHOr,

I dind't have much time to investigate.
I don't know, but to un-hidden you need to have "Unknown13" = "00" and "frame rate" = "00".
Unknown26 no need to change, but HD without Crypt have "00 00 01 00".

01 Crypt
00 un-hidden
01 ?
00 ?

Best regards,
KanalDecode

**Comment by KanalDecode** [comment]
Hi Filipe,

Check if channel 25 is it ok now?

[channel_list_UE40H6200_1201.scm.zip](https://github.com/PredatH0r/ChanSort/files/1424971/channel_list_UE40H6200_1201.scm.zip)

Regards,
KanalDecode

**Comment by PredatH0r** [comment]
Thank you both!
I updated the [test files](http://tox.beham.biz/permutations2.zip).
As mentioned earlier, 0_1010 is the one I expect to work for channel 19 (Sport TV 1). The others would be interesting to know if they work.

**Comment by FilipeAmadeuO** [comment]
KanalDecode
Yes. Channel 25 is ok now. It shows on the list. Perfect :)
Thanks

2017-10-29 11:31 GMT+00:00 KanalDecode <notifications@github.com>:

**Comment by FilipeAmadeuO** [comment]
PredatH0r:

Further testing :)
0_1010 -> OK
0_1000 -> OK
0_1100 -> NOK
0_1110 -> NOK
1_1000 -> NOK
1_1010 -> NOK
1_1100 -> NOK
1_1110 -> NOK

**Comment by KanalDecode** [comment]
Hi,

More info:
Unknown13 = Zap list "Program up, program down" - 00 (show)/ 01 (hidden)
Frame Rate = Guide list - 00 (show)/ 01 (hidden)
Unknown13 + Frame Rate = Channel List - 00 00 (show)/ 01 00 (hidden)/ 00 01 (hidden)

Check channels numbering list, hidden channels can have wrong list number.

**Comment by PredatH0r** [comment]
Thanks again for your feedback.
I just uploaded a new release of ChanSort to https://github.com/PredatH0r/ChanSort/releases/tag/v2017-10-29
"Unknown13" is now mapped to the "Skip" flag in the UI, the formerly called "FrameRate" field is now renamed and mapped to "Hidden".
In the UI you can multi-select any number of channels and use the right-mouse button context menu to set/clear the flags on all selected channels in one go.

**Comment by FilipeAmadeuO** [comment]
New version tested and working. Many thanks

**Comment by KanalDecode** [comment]
PredatHOr, thanks for the update.

Filipe, could you please email me?
kanaldecode@hotmail.com
