### ISSUE TITLE
Samsung K Series error

### ISSUE THREAD

**Issue by jonas7654** [PredatH0r/ChanSort#70]
I get this error while trying to import a .zip channellist from a Samsung K series TV.

![new bitmap image](https://cloud.githubusercontent.com/assets/26003949/26530579/c926e300-43d7-11e7-81c3-e1cc983ad27c.jpg)

**Comment by PredatH0r** [comment]
Hi jonas7654!
Could you provide me your channel list so I can replicate the problem?
I suspect that the .zip file is corrupted and cannot be read by ChanSort. 
This is a common problem on Samsung TVs when you are using a USB stick that is formatted with NTFS.
There are usually no problems when using a stick formatted with FAT32.
You can try Windows Explorer, WinZip or any other ZIP tool and see if the file is readable.
