### ISSUE TITLE
Import for Panasonic ZT60 failed

### ISSUE THREAD

**Issue by bitdeploy** [PredatH0r/ChanSort#71]
I'm unable to import the svl.db file exported from a Panasonic ZT60 (no plugin found...).
Please see attached file.

[svl.zip](https://github.com/PredatH0r/ChanSort/files/1120245/svl.zip)

regards,
Michael

**Comment by PredatH0r** [comment]
It's most likely that the Visual C++ 2010 x86 Redistributable Package wasn't installed (must be 2010 and x86). Otherwise ChanSort cannot read channel lists that use a SQLite database format.
Newer ChanSort versions now show a message box and offer to open the download page for that package.
