### ISSUE TITLE
Support for Comag-Reciver  (bin.dat)  

### ISSUE THREAD

**Issue by timbloo** [PredatH0r/ChanSort#72]
Does chansort also provide support for a comag receiver (PVR 100 ...)?
The comag file ends with a "bin" file. This is not recognized by chansort.

I uploaded the list to Zippyshare

http://www26.zippyshare.com/v/K629xYYW/file.html

**Comment by PredatH0r** [comment]
I'm not planning to add support for other formats due to the lack of technical documentation, test devices and time.
Sorry that I don't have any better news.
