### ISSUE TITLE
Samsung JU series

### ISSUE THREAD

**Issue by zacskomiklos** [PredatH0r/ChanSort#74]
Guys,
Anytime I am trying to open channel list under win10 64bit, always have the error message of "No plugin found to read/write ***.zip files". Have any idea to solve this issue?
Thx, Zacsi

**Comment by PredatH0r** [comment]
Most likely the Visual C++ 2010 Redistribution Package (x86) is not installed on the PC, which is needed for some types of channel lists. (The x64 package can't be used by ChanSort).
You can download it here: https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by zacskomiklos** [comment]
Perfect solution
thx a lot man!
