### ISSUE TITLE
Can't open channel list afterupdate to 1501 firmware on Samsung J series

### ISSUE THREAD

**Issue by ArndtW** [PredatH0r/ChanSort#77]
After udate to firmware level 1501 the saved cannel list cant be openend by the program.

Actual list is attached.
[Channel_list_T-HKMFDEUC-1501.3.zip](https://github.com/PredatH0r/ChanSort/files/1273077/Channel_list_T-HKMFDEUC-1501.3.zip)

**Comment by ArndtW** [comment]
Tried version 2016-08-10. This version runs fine with the firmware 1501. Actual version denies opening of zip-file.

**Comment by PredatH0r** [comment]
I can open your .zip file without any problems using version 2017-06-10 and see a DVB-C channel list in it.
What's the exact error message you get when you try to open the file?
The Samsung .zip format (and a few others) require that the Microsoft VC 2010 Redist (x86) package is installed on the system. Other versions (year or x64) are not compatible. I have no idea though why the older version would work without that installed.
You can download it from https://www.microsoft.com/en-us/download/details.aspx?id=5555
