### ISSUE TITLE
Weitere Filter nutzen?

### ISSUE THREAD

**Issue by swa01** [PredatH0r/ChanSort#8]
Hallo,

Kann ich irgendwie das Land oder die Sprache als Filter nutzen, um meine Liste von fast 1000 Sendern besser bearbeiten zu können?

Gruß,

Stefan

**Comment by PredatH0r** [comment]
Hallo Stefan,

leider sind in den Senderlisten keine Informationen über Land oder Sprache der einzelnen Sendern enthalten. Viele Listen enthalten nicht einmal Daten wie einen Audio-PID, den man eventuell in einem Verzeichnis nachschlagen könnte. Außerdem sind alle mir bekannten Verzeichnisdienste (z.B. Lyngsat) urheberrechtlich geschützt bzw. kostenpflichtig.
