### ISSUE TITLE
Panasonic TX-P50-S10E - r/w-module not found ...

### ISSUE THREAD

**Issue by kangaroo72** [PredatH0r/ChanSort#80]
Hi ...

I'm trying to sort the cannels on the Panasonic TX-P50-S10E (copied to SD-Card).
Samsung worked. For my file I got the error "Read/Write-Module not found ..."
Systemrequirements are installed.
I'm working on Windows 10 (latest version x64).
Any idea?

Thanks,

Tom

PS: svl attached ...
[svl_file.zip](https://github.com/PredatH0r/ChanSort/files/1346714/svl_file.zip)

**Comment by PredatH0r** [comment]
Unfortunately the format of this file is not supported by ChanSort.
For Panasonic TVs only files with extension .db and .bin are supported.
