### ISSUE TITLE
tv samsung serie  h 

### ISSUE THREAD

**Issue by leroi1** [PredatH0r/ChanSort#81]
hello I was trying to load a channel and I found this error
![schermata 2017-10-01 alle 14 22 

> 

- [
![schermata 2017-10-01 alle 14 22 53](https://user-images.githubusercontent.com/32437381/31057314-0de69c76-a6e1-11e7-9715-2fc1db75f7ca.png)
](`53](https://user-images.githubusercontent.com/32437381/31057310-e7730c5a-a6e0-11e7-999f-f1bcd2221177.png)`)

**Comment by PredatH0r** [comment]
You have to open the .zip or .scm file directly with ChanSort. Unzipping them first won't work.

**Comment by leroi1** [comment]
[map-AirD.zip](https://github.com/PredatH0r/ChanSort/files/1347492/map-AirD.zip)
this file is ok

**Comment by leroi1** [comment]
[map-AirD.zip](https://github.com/PredatH0r/ChanSort/files/1347496/map-AirD.zip)
it  ok file
