### ISSUE TITLE
Hisense H49N5705 read//write module not found

### ISSUE THREAD

**Issue by btx1980** [PredatH0r/ChanSort#82]
Hello, 

I'm trying to sort the cannels on my Hisense H49N5705 (copied to USB stick).
When I want to open the channel.db file I got the error "Read/Write-Module not found ..."

Systemrequirements are installed.

I'm working on Windows 7 (x64).

Any idea?

Many Thanks,

**Comment by PredatH0r** [comment]
Most likely you have the x64 version of the VC2010 Redist Package installed. ChanSort requires the x86 version. (Both can be installed on the same system).
Newer versions of ChanSort automatically detect the missing package and offer to open the download page for it. They also show more detailed information if the file couldn't be read for other reasons.
