### ISSUE TITLE
Support for Samsung MU6179?

### ISSUE THREAD

**Issue by MAGICCC** [PredatH0r/ChanSort#89]
I would like to edit my channels with this app, but unfortunately the mentioned series doesn't work. Any files I can send to help to support this sort of series?

**Comment by PredatH0r** [comment]
I haven't received any files for this series yet, so any help is appreciated. 
Can you please send me your channel list file to horst @ beham . biz?

**Comment by MAGICCC** [comment]
Thanks, I sent some mail

**Comment by PredatH0r** [comment]
Thanks!
I fixed a problem that occurred one time when I opened your list and haven't had any issues since.
Another owner of a Samsung MU model confirmed that the program worked fine for him.
The fixed version 2017-11-16 is available under Releases

**Comment by MAGICCC** [comment]
Oh cool, thanks for the fix!
